### ISSUE TITLE
https command not found after fresh installation

### ISSUE THREAD

**Issue by batjko** [httpie/httpie#1001]
Hi guys,

Any time I install httpie on Ubuntu (`sudo apt-get install httpie`), the `http` command works perfectly fine afterwards.

However, `https` is never found.

![image](https://user-images.githubusercontent.com/7287076/101105247-f712d200-35c4-11eb-8322-0058d53550e5.png)

I have had this on all machines where I tried this so far, WSL on Windows, as well as native Ubuntu 19.x and 20.x.
What do I need to do to get https command working as well, and what needs to change in the installation instructions, because I can't imagine I'm the only one encountering this?

**Comment by jakubroztocil** [comment]
@batjko it should work out of the box, but I can see the Ubuntu version very old. We’re working on having it updated to the latest 2.x. In the meantime, I’d recommend you installing HTTPie via pip.

**Comment by batjko** [comment]
Ok thanks, I'll try that instead.

**Comment by BoboTiG** [comment]
I close that issue as the root cause is #1003, let's focus on one issue.
