### ISSUE TITLE
HTTP/1.1 404 Not Found error

### ISSUE THREAD

**Issue by charujing** [httpie/httpie#1002]
(base) PS C:\Users\charu> http --stream -f -a Aaron https://stream.twitter.com/1/statuses/filter.json track='Justin Bieber'
http: password for Aaron@stream.twitter.com:
HTTP/1.1 404 Not Found
cache-control: no-cache, no-store, max-age=0
content-length: 0
date: Mon, 07 Dec 2020 03:12:59 GMT
server: tsa_a
set-cookie: personalization_id="v1_7M0qAqT4IHizTm3vckq/tQ=="; Max-Age=63072000; Expires=Wed, 07 Dec 2022 03:12:59 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None
set-cookie: guest_id=v1%3A160731077930093670; Max-Age=63072000; Expires=Wed, 07 Dec 2022 03:12:59 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None
strict-transport-security: max-age=631138519
x-connection-hash: bbc073d81faa811ca0a7bf6f7a3234b9
x-response-time: 5
x-tsa-request-body-time: 1

This is more information about environment.
Windows 10 professional, Python 3.8.3 (default, Jul 2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

**Comment by jakubroztocil** [comment]
Fixe. Thanks for the report, @charujing. 🥧
