### ISSUE TITLE
Output not properly displayed in UTF-8

### ISSUE THREAD

**Issue by mosesontheweb** [httpie/httpie#1010]
Hi,

I'm using httpie v.2.3.0, it's really wonderful! While playing around with my website today I encountered a strange effect while displaying the output. All special characters, like €(EUR) or Ä/Ö/Ü are not shown properly, it seems like there's encoding error. `curl` on the other side does the job correctly.

Here are the headers:
```
# http -F --headers stocksport1.at:
HTTP/1.1 200 OK
accept-ranges: bytes
age: 39
content-encoding: gzip
content-length: 854
content-type: text/html
date: Sun, 03 Jan 2021 11:20:03 GMT
etag: "6cb-5b0869f17f6b5"
last-modified: Wed, 30 Sep 2020 11:58:44 GMT
server: Apache
vary: Accept-Encoding

# curl stocksport1.at -L -D -
HTTP/1.1 200 OK
accept-ranges: bytes
age: 39
content-encoding: gzip
content-length: 854
content-type: text/html
date: Sun, 03 Jan 2021 11:20:03 GMT
etag: "6cb-5b0869f17f6b5"
last-modified: Wed, 30 Sep 2020 11:58:44 GMT
server: Apache
vary: Accept-Encoding
```
The charset is defined in the header of the HTML file, but i guess this isn't interpreted by httpie. So, what I'm doing wrong or what is httpie doing wrong?

Many thanks in advance, regards, Thomas

**Comment by Almad** [comment]
In theory, you should do `content-type: text/html; charset=utf-8`. 

In practice and in the spirit of usability, I think it would make sense for HTTPie to support additional encoding detection for well-known content types.

**Comment by jakubroztocil** [comment]
Related: #627 #594 #358

**Comment by Almad** [comment]
Now part of #1022
