### ISSUE TITLE
verbose output should show SSL/TLS details

### ISSUE THREAD

**Issue by pmeister** [httpie/httpie#1011]
I'd like the see httpie's verbose output include some details of the SSL handshake and certificate, like curl's verbose output does:

for example:

```
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384

* Server certificate:
*  subject: C=US; ST=California; L=Redwood Shores; O=Oracle Corporation; CN=webservices.netsuite.com
*  start date: May 20 00:00:00 2020 GMT
*  expire date: Aug 19 12:00:00 2021 GMT
*  subjectAltName: host "rest.netsuite.com" matched cert's "rest.netsuite.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert Secure Site ECC CA-1
*  SSL certificate verify ok.

```

**Comment by Almad** [comment]
This could be implemented as adding additional flags to `-p`, in this case potentially `S` for SSL?

It probably shouldn't be part of `--verbose` since it would break the pipe chainability with other commands.

**Comment by patpolster** [comment]
> I'd like the see httpie's verbose output include some details of the SSL handshake and certificate, like curl's verbose output does:
> 
> for example:
> 
> ```
> * SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384
> 
> * Server certificate:
> *  subject: C=US; ST=California; L=Redwood Shores; O=Oracle Corporation; CN=webservices.netsuite.com
> *  start date: May 20 00:00:00 2020 GMT
> *  expire date: Aug 19 12:00:00 2021 GMT
> *  subjectAltName: host "rest.netsuite.com" matched cert's "rest.netsuite.com"
> *  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert Secure Site ECC CA-1
> *  SSL certificate verify ok.
> ```

**Comment by kindlehl** [comment]
This would be very handy.

**Comment by isidentical** [comment]
Duplicate of #826.
