### ISSUE TITLE
Better handling of responses without correct content-type charset

### ISSUE THREAD

**Issue by Almad** [httpie/httpie#1022]
## Problem

If server doesn't provide correct content-type charset, we're defaulting to latin1 [because requests underlying does that](https://github.com/psf/requests/issues/2086). This is undesirable for user experience.

## Possible solutions

* Default to utf8
* For well-known content-types, handle them as defined in respective RFC (utf8 for `application/json`, first line or BOM for XML, meta tag in HTML)
* Use [chardet](https://pypi.org/project/chardet/) to detect from the body

## Considerations
* Streaming mode and chunks
* Discrepancies between streaming and display mode: should this only be done for readability when showing to the terminal, or also when piping to other commands? Current decision: only doing this for terminal display. Consider flag for enforcing this for piping as well
* chardet requires downloading the whole body, so it would download a whole video to tell you it's binary data

**Comment by Ousret** [comment]
Hi @Almad 

There could be a change that might interest you in the near future. see https://github.com/psf/requests/pull/5797

Personally, I think that Httpie should differ from the default process applied to content with unknown or incorrect charset declared. You should output something acceptable in the best possible way.

Let me be my own advocate 😃 With charset-normalizer : 

- No need for it to parse the whole body if binary.
- Will never output a charset if not decodable by the associated codec.
- Can verify preemptively and safely if the body does declare something (like in XML).
- Support for more charsets.
- Have good backward compatibility with Chardet. See referred PR.

There is also, could be, a license issue/conflict in your case. The dependency resolution makes Chardet a mandatory module, therefore, if Httpie would be shipped bundled in any form, this would be a problem.

Regards,

**Comment by Almad** [comment]
@Ousret Excellent! It's a bit unclear from the discussion: will that be merged into the requests or would we need to monkeypatch around?

**Comment by Ousret** [comment]
It is a full-on replacement of Chardet when using Python 3.

**Comment by Ousret** [comment]
Requests maintainers merged it. Should be tagged soon.

**Comment by Ousret** [comment]
The tag has been published.

**Comment by BoboTiG** [comment]
@Ousret I was trying the move from `chardet` to `charset-normalizer` but there is no behavior change:
```python
>>> import requests
>>> r = requests.get('https://zoek.officielebekendmakingen.nl/kst-34200-14/metadata_owms.xml')
>>> r.headers['Content-Type']
'text/xml'
>>> r.encoding
'ISO-8859-1'

# Check 1
>>> r.content[:38]
b'<?xml version="1.0" encoding="UTF-8"?>'

# Check 2
>>> requests.compat.chardet
<module 'charset_normalizer' from '/.../lib/python3.9/site-packages/charset_normalizer/__init__.py'>

# Check 3
>>> requests.compat.chardet.detect(r.content)
{'encoding': 'utf-8', 'language': 'English', 'confidence': 0.975}
```
So the new module is working fine, I had no doubt about that ;)
But `requests` does not seem to use it? Maybe I did something wrong while testing.

**Comment by Ousret** [comment]
Hi @BoboTiG 

You may want to call the property `apparent_encoding` instead. Requests only return a guessed encoding through that. And use it sometimes with the `.text()` method. 

```python
>>> import requests
>>> requests.__version__
'2.26.0'
>>> r = requests.get('https://zoek.officielebekendmakingen.nl/kst-34200-14/metadata_owms.xml')
>>> r.encoding
'ISO-8859-1'
>>> r.apparent_encoding
'utf-8'
```
Would be glad to see your feedback.

**Comment by BoboTiG** [comment]
Oh I see. Unfortunately it will not be so easy:
```shell
$ python -m httpie 'https://zoek.officielebekendmakingen.nl/kst-34200-14/metadata_owms.xml'
HTTP/1.1 200 OK
Cache-Control: private
Content-Disposition: inline; filename=metadata_owms.xml
Content-Encoding: gzip
Content-Length: 871
Content-Security-Policy: frame-ancestors 'self'
Content-Type: text/xml
Date: Thu, 15 Jul 2021 15:00:26 GMT
Expect-CT: enforce, max-age=30
Permissions-Policy: geolocation=(), midi=(), notifications=(), push=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), speaker=(), vibrate=(), fullscreen=(), payment=()
Referrer-Policy: strict-origin-when-cross-origin
Server: 
Strict-Transport-Security: max-age=31536000; includeSubDomains;
Vary: Accept-Encoding
X-AspNet-Version: 
X-AspNetMvc-Version: 
X-Content-Security-Policy: frame-ancestors 'self'
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: 
X-XSS-Protection: 1; mode=block
x-webkit-csp: frame-ancestors 'self'


__main__.py: error: RuntimeError: The content for this response was already consumed
```
`apparent_encoding` will consume `content`, and that is not something we want for HTTPie: https://github.com/httpie/httpie/blob/41c251ec7c537059b44c69b75b89c6dd671a25fc/httpie/models.py#L83-L91

Out of curiosity, do you see a workaround? :D

**Comment by BoboTiG** [comment]
The root cause seems to be in [get_encoding_from_headers()](https://github.com/psf/requests/blob/5351469472eccee7ed1a6cae53341446c520d807/requests/utils.py#L524-L525): it will return `ISO-8859-1` when `text` is part of the content type. It is not bad, it is just that we are based on that value to prevent fetching the whole body of a response.

**Comment by BoboTiG** [comment]
https://github.com/psf/requests/issues/2086 is interesting to follow.

**Comment by Ousret** [comment]
For now, my first choice would be to do it directly using `charset-normalizer` after HTTPie got the whole body. Or resetting the buffer seek if this is how it is done/checked.

**Comment by BoboTiG** [comment]
Yes, let me try something :)
