### ISSUE TITLE
Output errors reason when a request is failing with quiet option

### ISSUE THREAD

**Issue by soullivaneuh** [httpie/httpie#1026]
I use HTTPie on a script to convert images:

```bash
http --quiet --form --download --output "${png_path}" POST https://imagine.company.com/convert \
	stripmeta==true \
	lossless==true \
	type==png \
	background==white \
	file@"${svg_path}"
```

It works, but when it fail I don't have any information because of the `--quiet` option:

```
bash build.sh
HTTPie version: 2.3.0
assets/fa-pro/png/brands/500px.png
make: *** [Makefile:4: build] Error 5
```

On that case, I have a Bad Gateway error (504).

If I remove it, I have the information but also when it success (200).

It would be great to have the possibility to quiet the output except if it's a request error.

**Comment by Almad** [comment]
So something like `--quiet-on-success`?

**Comment by jakubroztocil** [comment]
@soullivaneuh You’re working on what looks like a scripted workflow. So you likely want to interrupt the flow if the request fails. For that, it’s better to rely on the exit status code than on the textual output.

You can use `--check-status`, to instruct HTTPie to check the response status and exit with a non-zero code if there has been a problem (see https://httpie.io/docs#scripting for more details):

```bash
if http --quiet --check-status httpbin.org/status/504 ; then
    echo "OK"
else 
    echo "ERROR: $?"
    exit 1
fi
# => ERROR: 5
```

To your question:  [`--quiet`](https://httpie.io/docs#quiet-output) is designed to suppress all output except for errors.  That’s how CLI tools typically implement it. What we’re missing is an error message for error responses (but only with `--check-status`):

When you apply `--check-status` and  the response indicates an error, then we correctly exit with a non-zero code, but we should also write an error message to `stderr` to play well with `--quiet`.

**Comment by jakubroztocil** [comment]
HTTPie 2.4.0 with this change has just been released 🥧

**Comment by soullivaneuh** [comment]
Wow, just opened an issue from 10 days and I got a new release with clear indications about how to solve my need.

Well done and thanks! I'll test this as soon as possible.
