### ISSUE TITLE
Why are httpie and service options request results different?

### ISSUE THREAD

**Issue by wajika** [httpie/httpie#1038]
First of all, I am not sure if there is a problem with my thinking.

Another thing, the domain name I requested is implemented by the windows dns server.

issue:
I found that the options request issued by the application got rich results, but I did not get similar results using httpie.

I want to get the  http.request.headers.Access-Control-Request-Headers field.

--------------------------------
Data captured in application:
![cors内容](https://user-images.githubusercontent.com/17058349/108942696-6ebb3f00-7692-11eb-941c-fab2dcb4c0d7.png)

--------------------------------

Httpie result
![httpie](https://user-images.githubusercontent.com/17058349/108943023-0751bf00-7693-11eb-9561-7c23965d852c.png)

--------------------------------

curl result
![curl](https://user-images.githubusercontent.com/17058349/108943039-0fa9fa00-7693-11eb-867c-706cb99c5266.png)

**Comment by Almad** [comment]
Could you clarify what you mean by "application"? Is it a one you are developing?

Either way, it seems that your application is sending extra headers (like `Access-Control-Request-Headers`) that you are not sending using HTTPie. If you want to reproduce the response, you should send them as well, e.g.

```
http pa.lonsid.cn Access-Control-Request-Headers:authorization,content-typeelastic-apm-traceparent
```

**Comment by Almad** [comment]
Closing for now as it's not an issue with HTTPie, but feel free to reach out with more questions / clarifications.
