### ISSUE TITLE
pip install error 

### ISSUE THREAD

**Issue by zwh-china** [httpie/httpie#1039]
The **setup.cfg** in the main folder of this project has a pair of unusual character which will result the following Error output
I add a print statement in dist.py it turns out to out put the file name:**setup.cfg**
![图片](https://user-images.githubusercontent.com/39894798/108997450-90d8af80-76da-11eb-8b5e-646974883f46.png)
So i run cat setup.cfg which prints this 
![图片](https://user-images.githubusercontent.com/39894798/108996993-114ae080-76da-11eb-927f-42f93c82bd5d.png)
I delete single quotes and everything went normal.

**Comment by Almad** [comment]
If someone visits from google: this is caused by system encoding being set to [GBK](https://en.wikipedia.org/wiki/GBK_(character_encoding)) which doesn't support full range of UTF-8 characters. Distutils use that encoding to interpret `setup.cfg` and typography quotes cause it to fail.
