### ISSUE TITLE
Consider joining efforts with xh in porting HTTPie to Rust

### ISSUE THREAD

**Issue by ducaale** [httpie/httpie#1043]
HTTPie is one of a few tools that I recommend to everyone. However, the language it is currently written in means it can suffer from slow startup and some occasional installation problems.

I and other lovely contributors have been working on [porting HTTPie to Rust](https://github.com/ducaale/xh). And given that an [official Rust version of HTTPie](https://crates.io/crates/httpie) is now being planned, we would love to help in any way we can.

**Comment by jakubroztocil** [comment]
Hey @ducaale, thanks for reaching out! I’ll shoot you an email.

**Comment by thernstig** [comment]
Please make this happen 👍 All of my most and best tooling is written in Rust due to it's significant speed advantage, and it being statically linked. It's just so nice.
