### ISSUE TITLE
shadow file name 'ssl.py' may cause run time error when tring to run the program from source code

### ISSUE THREAD

**Issue by zwh-china** [httpie/httpie#1044]
![image](https://user-images.githubusercontent.com/39894798/110198081-d17aba80-7e8a-11eb-9186-5b60765e1d2d.png)

As you can see in the screenshot in Pycharm, it shows that the ssl has no property named 'CERT_REQUIRED'. But when I looked up the official doc of urlib and pyopenssl. I am sure that it should not be that property doesn't exist. 

I reinstall the requirements and openssl plus urlib in the venv still not work. Then I think maybe the shadow name of ssl.py cause the problem. After rename the ssl.py everything went normal.

So I just change the name of ssl.py in the httpie folder and change the import name of ssl in the  httpie folder to solve this

**Comment by shimmeris** [comment]
Try using `python -m httpie.__main__` under the httpie directory which contains a README file. Since that's the root directory.

**Comment by elenalape** [comment]
Did @shimmeris's comment solve your issue @zwh-china?

**Comment by zwh-china** [comment]
Yes, I turned out to find my environment may cause the issue, I set up an venv and this problem did not appear again. And `python -m httpie.__main__` can properly invoke the program.
