### ISSUE TITLE
Content-Lenght header is one byte to big

### ISSUE THREAD

**Issue by cynay** [httpie/httpie#1046]
**Checklist**

- [x] I've searched for similar issues.
- [2.3.0] I'm using the the latest version of HTTPie.

---

**What are the steps to reproduce the problem?**

1. 
`echo "A" | http -v POST localhost:9999`
Request:
```POST / HTTP/1.1
Host: localhost:9999
User-Agent: HTTPie/2.3.0
Accept-Encoding: gzip, deflate
Accept: application/json, */*;q=0.5
Connection: keep-alive
Content-Type: application/json
Content-Length: 2

A
```

2. 
`curl -s -XPOST localhost:9999 --data A`
Request:
```POST / HTTP/1.1
Host: localhost:9999
User-Agent: curl/7.64.1
Accept: */*
Content-Length: 1
Content-Type: application/x-www-form-urlencoded

A
```

**What is the expected result?**
Header Content-Length: 1 !

**What happens instead?**
Header Content-Length: 2
I think there's a newline added.

**Debug output**
See top

**Comment by jakubroztocil** [comment]
@cynay `echo` by default adds a `\n` at the end. You can get rid of it with `echo -n`:

```bash
echo -n A | http --offline :9999
```

```http
POST / HTTP/1.1
Accept: application/json, */*;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 1
Content-Type: application/json
Host: localhost:9999
User-Agent: HTTPie/2.4.0

A
```
