### ISSUE TITLE
Feature request: load whole request from a file

### ISSUE THREAD

**Issue by ferenczy** [httpie/httpie#1047]
It's possible that HTTPie has such a feature already, but I was unsuccessful in trying to find it.

## What enhancement would you like to see?

To have a possibility to load the whole request (URL, HTTP method, headers, payload, etc.) from a file.

## What problem does it solve?

The use case is to have a library of requests stored as a hierarchy of directories and files. It should be platform-independent, so it works with HTTPie on any platform it runs on.

**What is it good for?**

When working on an API project, I want to have a library of API requests consisting of prepared complete request files that I can simply execute using HTTPie, so I don't have to look for URLs, headers, parameters, payloads, etc. in documentation or even in a source code every time I need to make a request.

Such library for a single project may look like the following:

    project
    |
    + users
    | |
    | + create.http
    | + update.http
    | + delete.http
    | + list.http
    |
    + products
      |
      ...

Currently, I'm always creating such a library for API request payloads, storing them in files. But that's not enough to make a request. I still have to look what URL, headers, and other parameters a specific API endpoint or request requires. I can have a separate library of HTTPie commands for each payload or search them in the shell history, but it would be great to have a single file containing everything needed to make a valid API request, so the only information I need to provide to HTTPie is that file:

    http --request project/users/list.http

HTTPie is currently even able to create those request files (see below), I just didn't find a way to load them.

### Possible solution using shell script

An easy solution would be to store request commands as shell scripts, for example `project/users/create.sh` might contain the following:

    http [parameters] [method] <url> < ./create.json

I would have two files for each request – a shell script and a payload file (if it needs one).

The problem with this solution is that it's platform-dependent. Those shell scripts would work with bash only.

### Proposed solution

I have managed to find a feature that is basically doing the first half of what I need. It's the [Offline mode](https://httpie.io/docs#offline-mode) and the `--offline` parameter. The following command saves the whole request including the payload into the file `request.http` (without actually sending any request):

    http --offline [parameters] [method] <url> < payload.json > request.http

The file it produces contains the whole RAW HTTP request as is being sent, everything needed to make a request:

    POST /api/endpoint HTTP/1.1
    User-Agent: HTTPie/2.3.0
    Accept-Encoding: gzip, deflate
    Accept: application/json, */*;q=0.5
    Connection: keep-alive
    Content-Type: application/json
    Content-Length: 8
    Host: test.dev

    payload

It's possible to send such request using for example netcat:

    nc <domain> <port> < request.http

But I didn't find a way to do the same with HTTPie. I have tried the analogy to the `nc` command (`http <domain> < request.http`), but HTTPie considers the file to be just a payload.

I would like to have a possibility similar to the following:

    http --request request.http

**How I would expect it to work:**

1. If a request file is provided, HTTPie reads all request parameters (URL, method, headers, payload, etc.) from there
2. If any parameter is provided on the command line, it overwrites the value from the request file

**Current issues:**

1. The URL parameter is mandatory. It would be nice to read it from the file also, but if it would be against the HTTPie's design, it wouldn't be a big issue. I can provide only the domain part in the URL parameter and have the whole URL path part loaded from the file.
2. HTTPie can save the request to a file but it cannot read it back, or I didn't find a way to do that.

### Alternative solution

Everything is the same as in the proposed solution, but instead of RAW HTTP request data, the request file contains HTTPie parameters in some form (e.g. similar to default options in the `config.json` file).

**Comment by danslapman** [comment]
Actually duplicates #758

**Comment by ferenczy** [comment]
@danslapman Yeah, it looks like the same thing, so this issue may be closed as a duplicate, thank you.

**Comment by elenalape** [comment]
Closing as duplicate. Thanks for the request, though!
