### ISSUE TITLE
brew install httpie will install python too instead of using my existing pyhton

### ISSUE THREAD

**Issue by qiulang** [httpie/httpie#1051]
**Checklist**

- [x] I've searched for similar issues.
- [x] I'm using the the latest version of HTTPie.

---

**What are the steps to reproduce the problem?**

1. MacOS 11.2.3 (Big Sur) has python 3.8 installed and most of my projects use python 3.8
2. I installed httpie using `brew install httpie` then brew installed python 3.9 as well and updated my system python3 to that.
3. I know it is not necessarily the htppie's bug but is it possbile to use my system python 3.8 instead of install 3.9 (and without my notice at all) ?

Thanks

**Comment by JimiPedros** [comment]
seems like HTTPie setups a virtual environment with a version of Python 3.6 then activates this virtual environment, if you `deactivate` will your system be using Python 3.8? Just a guess - I'm not very familiar with HTTPie 🤷

**Comment by elenalape** [comment]
Looking at the [homebrew formula for HTTPie](https://github.com/Homebrew/homebrew-core/blob/master/Formula/httpie.rb), `depends_on "python@3.9"` is possibly what is installing 3.9 on your system. @jakubroztocil may be able to provide more context on why that is the case.

However, installing HTTPie using Homebrew doesn't seem to change my _default_ system version of python 🤔 Is that definitely the case for you? @qiulang please can you share what the output of running `python --version` (or `python3 --version`) is?

**Comment by jakubroztocil** [comment]
The HTTPie package is fully managed by Homebrew, so it doesn’t depend on the system Python. That is a big advantage because the macOS Python version tends to get quite old. 

As @elenalape points out, your system Python should be unaffected, though. Please take a look here to learn more about how Python and Homebrew work together: https://docs.brew.sh/Homebrew-and-Python

**Comment by qiulang** [comment]
Hi macOS 11.2.3 has upgraded system python3 to 3.9 but I will try to find another mac to retry it.

**Comment by qiulang** [comment]
Hi I reproduced the case, please check:

```
lang@localhost ~ % which python3
/usr/bin/python3
lang@localhost ~ % python3 --version
Python 3.8.2
lang@localhost ~ % brew list
==> Formulae
autoconf	m4		node-build	openssl@1.1	pyenv		sqlite
gdbm		mpdecimal	nodenv		pkg-config	readline	xz
lang@localhost ~ % brew install httpie
...
==> Caveats
==> python@3.9
Python has been installed as
 /usr/local/bin/python3
```

Then
```
lang@localhost ~ % python3 --version
Python 3.9.2
//I think it is because the PATH setting
lang@localhost ~ % echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by jakubroztocil** [comment]
@qiulang Homebrew puts `python3` on your `$PATH` but leaves the version-less `python` intact so you can use to refer to the system Python. This has nothing to do with HTTPie, though — https://docs.brew.sh/Homebrew-and-Python.

**Comment by qiulang** [comment]
@jakubroztocil  I read that brew document when you first pointed to me. But what that document didn't explain and what confused me is following, as I tried to brew install httpie on my 3rd mac.

As you can see it said python 3.9 is installed at `/usr/local/bin/python3` but when I check its version, it is still 3.6.4 as it still points to the python version I install through python installer from https://www.python.org/downloads/mac-osx/.

Maybe I need to further consult with brew but since we have got here I show my problem here first.

```
xiaofangdeiMac:bin qiulang$ brew info python
python@3.9: stable 3.9.1
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python@3.9/3.9.1_6 (8,665 files, 126.4MB)
  Built from source on 2021-05-06 at 14:22:13
From: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git/Formula/python@3.9.rb
License: Python-2.0
==> Dependencies
Build: pkg-config ✔
Required: gdbm ✔, openssl@1.1 ✔, readline ✔, sqlite ✔, tcl-tk ✔, xz ✔
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.9/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.9/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Analytics
install: 670,489 (30 days), 2,219,324 (90 days), 5,170,195 (365 days)
install-on-request: 234,190 (30 days), 757,400 (90 days), 1,542,873 (365 days)
build-error: 0 (30 days)
xiaofangdeiMac:bin qiulang$ /usr/local/bin/python3 --version
Python 3.6.4
xiaofangdeiMac:bin qiulang$ ls -al /usr/local/bin/python3
lrwxr-xr-x  1 fengchunyan  wheel  69  3 12  2018 /usr/local/bin/python3 -> ../../../Library/Frameworks/Python.framework/Versions/3.6/bin/python3
```

**Comment by qiulang** [comment]
But from a user point of view if I uninstall a tool I just want everything comes with it uninstalled too.

**Comment by jakubroztocil** [comment]
Noted
