### ISSUE TITLE
[Poll] Raw request body option name

### ISSUE THREAD

**Issue by BoboTiG** [httpie/httpie#1063]
In order to tackle #534, we would like to ask for the community assistance to find the most approprite option name :)

In short, we are implementing a way to specify the raw request body. Example:
```shell
$ http --new-option 'My name is John' --offline pie.dev/post
POST /post HTTP/1.1
Accept: application/json, */*;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 15
Content-Type: application/json
Host: pie.dev
User-Agent: HTTPie/2.5.0-dev

My name is John
```
It is an alternative to passing the body via `STDIN`:
```shell
$ echo -n 'My name is John' | http --offline pie.dev/post
POST /post HTTP/1.1
Accept: application/json, */*;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 15
Content-Type: application/json
Host: pie.dev
User-Agent: HTTPie/2.5.0-dev

My name is John
```

I will add a comment per suggestion and you will only have to :+1: or :-1: to let us know your preference.
If you have suggestions, feel free to comment too.

---

Here is the list of used names that cannot be chosen again:
- `body, -b`
- `-c`
- `-d`
- `-p`, `-P`

**Comment by BoboTiG** [comment]
`--input, -i`

**Comment by BoboTiG** [comment]
`--data`

**Comment by BoboTiG** [comment]
`--message, -m`

**Comment by BoboTiG** [comment]
`--payload`

**Comment by elenalape** [comment]
If it's a raw request body, what do you think about `--raw`?

**Comment by BoboTiG** [comment]
Then `--raw` is will be!
Thanks everyone for your participation :)
