### ISSUE TITLE
Prompted passwords are not properly persisted into sessions

### ISSUE THREAD

**Issue by blyxxyz** [httpie/httpie#1098]
**What are the steps to reproduce the problem?**

1. While using a session, supply only a username to `--auth` so the password is prompted. e.g. `http --offline --session ./sess.json --auth user :`
2. Send a new request using the session without explicit authentication, e.g. `http --offline --session ./sess.json :`

**What is the expected result?**

One of the following:
- The password I entered last time is sent
- I have to enter my password again

(Which of these would be desirable? We're implementing sessions in ducaale/xh#125 and would like to stay compatible)

**What happens instead?**

In the new request, the password is sent as `None`.

**Example**

```console
$ http --offline --session ./sess.json --auth user :
http: password for user@localhost: pass
GET / HTTP/1.1
[...]
Authorization: Basic dXNlcjpwYXNz
[...]

$ echo dXNlcjpwYXNz | base64 -d
user:pass

$ http --offline --session ./sess.json :
GET / HTTP/1.1
[...]
Authorization: Basic dXNlcjpOb25l
[...]

$ echo dXNlcjpOb25l | base64 -d
user:None

$ cat sess.json
[...]
    "auth": {
        "raw_auth": "user",
        "type": "basic"
    },
[...]
```

**Comment by isidentical** [comment]
Fixed by #1239
