### ISSUE TITLE
macOS 12 compatible 

### ISSUE THREAD

**Issue by lienide** [httpie/httpie#1122]
**Checklist**

- [ ] I've searched for similar feature requests.

---

**What enhancement would you like to see?**

**What problem does it solve?**

E.g. “I'm always frustrated when [...]”, “I’m trying to do […] so that […]”.

**Provide any additional information, screenshots, or code examples below:**

**Comment by BoboTiG** [comment]
What is the problem? Could you elaborate please?

**Comment by lienide** [comment]
> What is the problem? Could you elaborate please?

Hi, I just want install httpie to my another mac and then see below:

```bash
brew install httpie
Warning: You are using macOS 12.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

Error: httpie: no bottle available!
You can try to install from source with:
  brew install --build-from-source httpie
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

and `brew install --build-from-source httpie` cmd execute failed

**Comment by BoboTiG** [comment]
What is the output of `brew install --build-from-source httpie`?
I am afraid we will not support such an old version, you would better install it through Python:
```shell
$ python3 -m pip install --upgrade httpie
```
That will install `http`& `https` executables just like `brew`.

**Comment by lienide** [comment]
Yes that's working! Thanks
