### ISSUE TITLE
Reader View for HTML websites

### ISSUE THREAD

**Issue by brasilikum** [httpie/httpie#1132]
**Checklist**

- [x] I've searched for similar feature requests.

---

**What enhancement would you like to see?**
I would like to have a representation of the HTML similar to "reader view" in many browsers.

**What problem does it solve?**

I am frustrated to scroll through pages of HTML on the CLI when there could be a more readable version made available.

**Provide any additional information, screenshots, or code examples below:**

**Comment by emdneto** [comment]
You can simply save the content and open it in firefox:

```bash
$ http https://www.lipsum.com/ -o file.html
$ firefox file.html
```

**Comment by brasilikum** [comment]
Hey @emdneto that would be a way to do it, but for me, it defeats the purpose.
If I had wanted to look at it in a browser, I could have done so directly.

My use case is automated fetching of a text only version for my personal notes.

**Comment by emdneto** [comment]
> Hey @emdneto that would be a way to do it, but for me, it defeats the purpose.
> If I had wanted to look at it in a browser, I could have done so directly.
> 
> My use case is automated fetching of a text only version for my personal notes.

I see. In this case, I believe that we can't perform a "text dump" by using httpie. But in the meantime, could you please try `lynx`? It may solve your use case:

```
$ sudo apt install lynx
```

```
$ lynx --dump https://www.lipsum.com/
```
