### ISSUE TITLE
HTTP request hangs for some site

### ISSUE THREAD

**Issue by arloan** [httpie/httpie#1138]
**Checklist**

- [x] I've searched for similar issues.
- [x] I'm using the latest version of HTTPie.

---

**What are the steps to reproduce the problem?**

1. hit the "Try Online" button of the homepage of https://httpie.io/
2. input command 'http https://www.cmegroup.com' and hit Enter
3. the output hangs without response body

**What is the expected result?**
The response body text (web page source codes)

**What happens instead?**
None. Empty.

**Debug output**

Please re-run the command with `--debug`, then copy the entire command & output and paste both below:

```
~ $ http --debug https://www.cmegroup.com
HTTPie 2.4.0
Requests 2.26.0
Pygments 2.9.0
Python 3.7.6 (default, Jan 30 2020, 09:44:41) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
/usr/bin/python3
Linux 4.18.0-147.3.1.el8_1.x86_64

<Environment {'colors': 256,
 'config': {'default_options': ['--style=monokai']},
 'config_dir': PosixPath('/home/termible/.httpie'),
 'devnull': <property object at 0x7fbe6e995a10>,
 'is_windows': False,
 'log_error': <function Environment.log_error at 0x7fbe6e99a5f0>,
 'program_name': 'http',
 'stderr': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>,
 'stderr_isatty': True,
 'stdin': <_io.TextIOWrapper name='<stdin>' mode='r' encoding='UTF-8'>,
 'stdin_encoding': 'UTF-8',
 'stdin_isatty': True,
 'stdout': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>,
 'stdout_encoding': 'UTF-8',
 'stdout_isatty': True}>

>>> requests.request(**{'auth': None,
 'data': RequestJSONDataDict(),
 'headers': {'User-Agent': b'HTTPie/2.4.0'},
 'method': 'get',
 'params': <generator object MultiValueOrderedDict.items at 0x7fbe6e8ce4d0>,
 'url': 'https://www.cmegroup.com'})
```

**Provide any additional information, screenshots, or code examples below:**
The same problem occurs for https://www.nasdaq.com, while good for https://www.bing.com and many others.

**Comment by zhan9san** [comment]
This maybe network issue.

I verified all sites above work well with `httpie`.

**Comment by isidentical** [comment]
I also verified the website in the given reproducer works correctly on the latest revision. If you still experience this issue, please let us know.
