### ISSUE TITLE
Do not append missing XML declaration in formatted responses

### ISSUE THREAD

**Issue by BoboTiG** [httpie/httpie#1156]
## Minimal reproduction code and steps

1. Create the file `repro.xml` with that content:

  ```xml
  <!-- comment --><root><element key='value'>text</element><element>text</element>tail<empty-element/></root>
  ```
2. Serve that file using:

  ```bash
  $ python -m http.server
  ```
3. And GET the file:

  ```bash
  $ http :8000/repro.xml
  ```

## Current result

```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- comment -->
<root>
  <element key="value">text</element>
  <element>text</element>
  tail
  <empty-element/>
</root>
```

Note the additional XML declaration (it is not present from the original response).

## Expected result

The responses should not be altered:

```xml
<!-- comment -->
<root>
  <element key="value">text</element>
  <element>text</element>
  tail
  <empty-element/>
</root>
```

---

## Additional information, screenshots, or code examples

When pretty-printing a XML response that does not contain a XML declaration, `minidom` will append one ([source](https://github.com/python/cpython/blob/851811f5772c43f72f445e2ce1ac3ea9da951ae3/Lib/xml/dom/minidom.py#L1823)).

**Comment by BoboTiG** [comment]
Of course @this-is-r-gaurav 👍 :)

**Comment by this-is-r-gaurav** [comment]
Its a dirty hack, not sure whether its acceptable, if any further suggestion i can update it @BoboTiG  https://github.com/httpie/httpie/pull/1183
