### ISSUE TITLE
Possible SQL injection vector through string-based query construction.

### ISSUE THREAD

**Issue by ByteHackr** [httpie/httpie#1170]
## Checklist

- [x] I've searched for similar issues.
- [x] I'm using the latest version of HTTPie.

---

Possible SQL injection vector through string-based query construction.

Location: superset/tests/integration_tests/csv_upload_tests.py:373

372             .get_sqla_engine()
373             .execute(f"SELECT * from {EXCEL_UPLOAD_TABLE}")
374             .fetchall()

Solution :
Sanitize and control the input data when building such SQL statement strings.

**Comment by jakubroztocil** [comment]
This is not httpie-related.
