### ISSUE TITLE
Method POST is used always when executing from go as external command

### ISSUE THREAD

**Issue by vishr** [httpie/httpie#1171]
## Checklist

- [x] I've searched for similar issues.
- [x] I'm using the latest version of HTTPie.

---

## Minimal reproduction code and steps

```go
package main

import (
	"fmt"
	"os/exec"
	"strings"
)

func main() {
	cmd := exec.Command("http", "-v", "--download", "pie.dev/image/png")
	cmd.Stdin = strings.NewReader("some input")
	out, err := cmd.CombinedOutput()
	fmt.Printf("error:%v, output=%s", err, out)
}
```

1.  Install go
2. Save above code as `test.go`
3. Execute `http` using `go run test.go`
4. `http` in this case is always using POST method

## Current result

```sh
❯ go run run.go
error:exit status 4, output=POST /image/png HTTP/1.1
User-Agent: HTTPie/2.5.0
Accept-Encoding: identity
Accept: application/json, */*;q=0.5
Connection: keep-alive
Content-Type: application/json
Content-Length: 10
Host: pie.dev

some input


http: warning: HTTP 405 Method Not Allowed

HTTP/1.1 405 Method Not Allowed
Date: Fri, 01 Oct 2021 20:02:08 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
allow: GET, OPTIONS, HEAD
access-control-allow-origin: *
access-control-allow-credentials: true
CF-Cache-Status: DYNAMIC
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=ZozyDmaSZ4O2KT0heUm24MDsaELjcsDSJgpkGrYIgeyPYCMaIPP2czSzaQy2GXyasl63Myp3ywWJpo%2Fg52z6LW6QAcnqiodkmAjxdXZUkepC6hUMzWIX4%2BwS"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 69784974dc1192f8-SJC
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400
```

## Expected result

Downloads a file

## Debug output

Please re-run the command with `--debug`, then copy the entire command & output and paste both below:

```bash
❯ go run run.go
error:exit status 4, output=HTTPie 2.5.0
Requests 2.26.0
Pygments 2.10.0
Python 3.9.7 (default, Sep  3 2021, 12:37:55)
[Clang 12.0.5 (clang-1205.0.22.9)]
/usr/local/Cellar/httpie/2.5.0/libexec/bin/python3.9
Darwin 20.6.0

<Environment {'colors': 256,
 'config': {'default_options': []},
 'config_dir': PosixPath('/Users/vr/.config/httpie'),
 'devnull': <property object at 0x10f92eb30>,
 'is_windows': False,
 'log_error': <function Environment.log_error at 0x10f9334c0>,
 'program_name': 'http',
 'stderr': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'stderr_isatty': False,
 'stdin': <_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'>,
 'stdin_encoding': 'utf-8',
 'stdin_isatty': False,
 'stdout': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>,
 'stdout_encoding': 'utf-8',
 'stdout_isatty': False}>

>>> requests.request(**{'auth': None,
 'data': b'some input',
 'headers': {'User-Agent': b'HTTPie/2.5.0', 'Accept': b'application/json, */*;q=0.5', 'Content-Type': b'application/json', 'Accept-Encoding': b'identity'},
 'method': 'post',
 'params': <generator object MultiValueOrderedDict.items at 0x10f9e7f20>,
 'url': 'http://pie.dev/image/png'})


http: warning: HTTP 405 Method Not Allowed
```

**Comment by jakubroztocil** [comment]
@vishr you might need to add `--ignore-stdin`, see https://httpie.io/docs#scripting

**Comment by vishr** [comment]
@jakubroztocil It worked but now the output is going to stdout. Also, is there a way to globally set this flag?

**Comment by jakubroztocil** [comment]
@vishr when invoking HTTPie from a context like the Go program, both `stdin` and `stdout` are disconnected from the terminal. And HTTPie interprets that as if being invoked as part of a Unix pipe chain where it adjusts its behavior. I.e., It thinks you’re trying to do something like this (your script is the middle command): 

```bash
echo foo | http --download pie.dev/post | http pie.dev/post
``` 

This makes sense when actually piping, but requires some explicit overwriting in use cases like yours.

You make it ignore `stdin` via the `--ignore-stdin` option mentioned above. And to make it `--download` the response body to a file, you need to explicitly specify the filename via `--output=file.txt` (https://httpie.io/docs#piping-while-downloading).

So something like:

```go
package main

import (
	"fmt"
	"os/exec"
	"strings"
)

func main() {
	cmd := exec.Command("http", "-v", "--ignore-stdin", "--download", "--output=image.png", "pie.dev/image/png")
	cmd.Stdin = strings.NewReader("some input")
	out, err := cmd.CombinedOutput()
	fmt.Printf("error:%v, output=%s", err, out)
}
```

**Comment by jakubroztocil** [comment]
> Also, is there a way to globally set this flag?

You can add it to your [config file](https://httpie.io/docs#config) in the `default_options` list. But I advise against it unless you have a strong reason because it’s a drastic change to the default behavior. But if you do go ahead with it, you can still un-set it for individual invocations via [`--no-ignore-stdin`](https://httpie.io/docs#un-setting-previously-specified-options).

**Comment by vishr** [comment]
Thank you. Will close.
