### ISSUE TITLE
Drop Python 3.6. support in Dec due to EOL

### ISSUE THREAD

**Issue by BoboTiG** [httpie/httpie#1177]
A friendly note to all our community: HTTPie will **drop Python 3.6 support by January, 2022**. Indeed, the Python Software Foundation will cease to maintain it by [December, 2021](https://www.python.org/dev/peps/pep-0494/#lifespan).

For those who may ask why: our rational is to drop insecure versions immediately when that happens.

That issue will be used a a reminder of tasks to be done in order to clean-up the code for such removal.

**Comment by jakubroztocil** [comment]
cd877a5e0875bfc27d560956b21230e65ad8c347
