### ISSUE TITLE
majed

### ISSUE THREAD

**Issue by testt11114** [httpie/httpie#1192]
## Checklist

- [x] I've searched for similar issues.
- [x] I'm using the latest version of HTTPie.

---

## Minimal reproduction code and steps

1.
2.
3.

## Current result

…

## Expected result

…

---

## Debug output

Please re-run the command with `--debug`, then copy the entire command & output and paste both below:

```bash
$ http --debug <COMPLETE ARGUMENT LIST THAT TRIGGERS THE ERROR>
<COMPLETE OUTPUT>
```

## Additional information, screenshots, or code examples

…

**Comment by isidentical** [comment]
This seems like a spam.
