### ISSUE TITLE
:// to use command name for scheme

### ISSUE THREAD

**Issue by sevenc-nanashi** [httpie/httpie#1195]
## Checklist

- [x] I've searched for similar feature requests.

---

## Enhancement request

`://` for `use command name for scheme`, like this:
```
http ://example.com 
--> http://example.com
https ://example.com
 --> https://example.com
```

---

## Problem it solves

This will make requesting from clipboard more easy, it's just putting space.

---

## Additional information, screenshots, or code examples

…

**Comment by jakubroztocil** [comment]
@sevenc-nanashi thanks for the suggestion — implemented in `master` 🎉
