### ISSUE TITLE
GUI/CLI interface for saving requests

### ISSUE THREAD

**Issue by pjalsGit** [httpie/httpie#1196]
## Checklist

- [x] I've searched for similar feature requests.

---

## Enhancement request

Add a GUI/CLI interface for saving requests.

---

## Problem it solves

It makes it easier to remember/debug requests.

---

## Additional information, screenshots, or code examples

Similar to Insomnia or Postman

## Search Terms (this should be added to the template by the way)
postman insomnia gui cli saving requests

**Comment by jakubroztocil** [comment]
Check this out: https://httpie.io/product

**Comment by isidentical** [comment]
Closing as resolved, with [HTTPie for Web & Desktop](https://httpie.io/app).

**Comment by jakubroztocil** [comment]
By the way, you’ll soon be able to work with your HTTPie data from the CLI as well.
