### ISSUE TITLE
Response headers sharing the same names get converted into a comma-separated list

### ISSUE THREAD

**Issue by jakubroztocil** [httpie/httpie#1207]
## Checklist

- [x] I've searched for similar issues.
- [x] I'm using the latest version of HTTPie.

---

## Minimal reproduction code and steps

Make a request to URL that returns repeated headers lines. Here’s an example express server that does that:

```js
// server.js
const express = require('express')
const fs = require('fs')

const app = express()
const port = 4000

app.get('/', (req, res) => {
  res.set('x-foo', ['bar', 'baz'])
  res.send('Hello World!')
})

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})
```

The run `node server.js` and get the response:

```bash
http :4000
```

## Current result

```http
x-foo: bar, baz
```

## Expected result

```http
x-foo: bar
x-foo: baz
```

---

@isidentical we’ve fixed this for requests, so let’s fix it for the responses as well.

**Comment by isidentical** [comment]
Seems like this happen during the adapter, so we should be able to simply build our own `HTTPAdapter` and use the actual values from the `urllib3`'s `HeaderDict`. Will send a patch!
