### ISSUE TITLE
Lazily load pygments styles

### ISSUE THREAD

**Issue by isidentical** [httpie/httpie#1211]
We currently try to retrieve all pygments styles at once, but this operation is very slow due to the import of `pkg_resources` on the pygments side.
https://github.com/httpie/httpie/blob/cfcd7413d1afbabc5ab3c88a892851335be4944a/httpie/output/formatters/colors.py#L31 

We should load these styles lazily when a user specifies `--style` explicitly.

**Comment by isidentical** [comment]
|               | normal   | lazy loading | factor      |
|---------------|----------|--------------|-------------|
| Environment 1 | 238.2 ms | 185.4 ms     | 1.30X (30%) |
| Environment 2 | 383.3 ms | 240.4 ms     | 1.58X (58%) |

Since the actual load we are removing is `pkg_resources` import, the speed-up factor is very dependant on how complex the current python environment you are within. The `Environment 1` is simply a fresh python docker image with only `httpie` installed. The `Environment 2` is my local environment with over 300+ python packages.

**Comment by isidentical** [comment]
(I'll send a patch after #1200)

**Comment by jakubroztocil** [comment]
Nice! 

Could we do some quick lookup even if the user specifies `--style`? Many users probably have `--style` in their config file. 

The full list is probably only needed for `--help' output. But also even then we only need the names.

**Comment by isidentical** [comment]
> Could we do some quick lookup even if the user specifies --style? Many users probably have --style in their config file.

If users specify `--style`, they will load the whole pygments (including all of it's plugins). And it will be like the original, so we will error out if the style is not available etc.

> The full list is probably only needed for --help output. But also even then we only need the names.

Yea, that is definitely the trickiest thing to do. The names and the actual styles don't matter much since either way the most of the time is spent on collecting packages through `pkg_resources`.

We need to retrieve the full list on 3 occasions;
- When you pass a valid `--style` (to verify it exists)
- When you pass an invalid `--style` (to print all the choices)
- To format the help message when run with `--help`.

**Comment by jakubroztocil** [comment]
> When you pass a valid --style (to verify it exists)

Couldn’t we use a different method for checking if it exists (e.g. checking if a module exists first, and only then loading the styles if not)? If I use a custom `--style` (via config, for example), I won’t be able to benefit from this optimization.

**Comment by isidentical** [comment]
> Couldn’t we use a different method for checking if it exists (e.g. checking if a module exists first, and only then loading the styles if not)?

We could introduce layers (e.g `check if this is a built-in httpie style > check if this is a built-in pygments style > check if this is coming from a pygments plugin`), but I think that would be a bit complicated.

Another possibility is asking pygments maintainers whether they would accept a patch that migrates from `pkg_resources` to `importlib_metadata` (a much much faster version for iterating over entry points), if the use case where a `--style` is also important to us.
