### ISSUE TITLE
Move away from Make

### ISSUE THREAD

**Issue by josephworks** [httpie/httpie#1214]
I see that this is a python project, but Make is being used for building/developer setup. Could make be replaced with a python script? Is there any specific reason why make was specifically used for this?

**Comment by doublevcodes** [comment]
I'd like to propose the use of Poetry for this project as well, and if that isn't feasible, perhaps Pipenv

**Comment by isidentical** [comment]
For the code-style checks, I am planning to introduce `pre-commit` in the future. But for the rest, my opinion is that, `Make` is alright.

> I see that this is a python project, but Make is being used for building/developer setup.

`Make` is a language-agnostic tool, are there any reasons to move away from it? 

> Could make be replaced with a python script? Is there any specific reason why make was specifically used for this?

If it didn't exist, I'd probably use `nox` for these sort of tasks but since we already have a `Makefile` I personally don't see any reasons to switch.

**Comment by josephworks** [comment]
Imo it would be nice to have a pure python project, where an external tool like make isn't part of the equation. 

Couldn't make easily be replaced with a python script?

I was using python on my phone, and I didn't have make installed so that costed me a few minutes.

**Comment by isidentical** [comment]
GNU Make is an essential part of nearly all development ecosystems, and AFAIK on many systems it actually comes bundled with the system. I don't know about android or other esoteric development environments, but if it is not available (which  is extremely unlikely), you actually don't need it at all.

CI runs everything you need to do, so don't worry much about it. You can manually run the tests locally with `pytest`.

**Comment by josephworks** [comment]
Most Linux distros use make for Linux updates iirc. Otherwise it is
primarily used for C and C++. I still don't see why make is used for this
specific project. Can it do the job? Yes. Should it be doing the job? Not
quite sure but I'm thinking no.

If I were to replace make with a python script, would that be accepted?

Python is cross platform also, but make does not come installed to windows
and (I think) Mac by default, another reason to not use it over a python
script.

**Comment by isidentical** [comment]
> I still don't see why make is used for this specific project. 

The most obvious answer I can give (as someone who has no context of it) is that, it was there and it works.

> If I were to replace make with a python script, would that be accepted?

I personally don't see any benefit of replacing something that already works with an ad-hoc python script.

**Comment by jakubroztocil** [comment]
@josephworks Makefiles are used for all sorts of purposes. Ours is it to have named commands that run other commands. That is perfectly common. There’s no strong reason to move that from the shell to Python. We’re building for the shell/terminal, after all.

I do understand it’s tempting, though — I’ve done it in the past myself (with a lot of effort and a poor result). Your initiative is appreciated, but maybe some of these issues would be more suited: https://github.com/httpie/httpie/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22
