### ISSUE TITLE
The HTTPie beta web interface can be accessed unauthenticated at a specific url.

### ISSUE THREAD

**Issue by markrosenbaum** [httpie/httpie#1217]
By going to a specific url you can access the HTTPie beta web interface unauthenticated.

Steps to reproduce:
Look at the `x-vercel-deployment-url:`  HTTP Header

**Comment by jakubroztocil** [comment]
@markrosenbaum thank you for the report! Where did you see the header? 🤔  Maybe could you please ping me on [our discord](https://httpie.io/discord) (I’m `@jakub`)?

Btw, accessing these URLs bypasses the private-beta-user check, but it’s not a vulnerability (I’ve updated the description a bit).

**Comment by markrosenbaum** [comment]
Thanks for the quick reply. I do not currently have a discord account, Do you have another way to chat?

**Comment by jakubroztocil** [comment]
> Do you have another way to chat?
@markrosenbaum email / Twitter (links on my profile)

**Comment by markrosenbaum** [comment]
Ok, I'l send the link to your email.

**Comment by markrosenbaum** [comment]
Look at the first one in the list.

**Comment by jakubroztocil** [comment]
The headers issue has been fixed, thank you!
