### ISSUE TITLE
Support timing output similar to Curl's -w option

### ISSUE THREAD

**Issue by marklap** [httpie/httpie#122]
Similar to timing output options in [Curl's -w argument](http://curl.haxx.se/docs/manpage.html#-w), and [the data you see using browser debug tools that produce those pretty waterfall charts](http://www.softwareishard.com/blog/har-12-spec/#timings). A custom [requests connection adapter](https://github.com/kennethreitz/requests/blob/master/requests/adapters.py) might do the job.

**Comment by GuiSim** [comment]
Any progress on this feature?

**Comment by jorisroovers** [comment]
Also interested in having some basic way of getting the total request+response time

**Comment by svagi** [comment]
+1

**Comment by marklap** [comment]
I threw this together for fun. It's not awesome but it works and I think it's a bit more accurate than some other attempts (or suggestions).

https://github.com/marklap/httpie-timing

**Comment by netroby** [comment]
+ 1

**Comment by doc** [comment]
+1

**Comment by cristian0** [comment]
+1

**Comment by WalterInSH** [comment]
+1
-w argument  is pretty useful

**Comment by johan-lejdung** [comment]
I'd really see a need for this, are there any plans to implement it?

**Comment by plo-** [comment]
Any news?

**Comment by danieleteti** [comment]
News?

**Comment by jakubroztocil** [comment]
Canonical issue: #243

**Comment by linpan** [comment]
Canonical issue so weird
