### ISSUE TITLE
`--json` without request items omits body instead of sending empty object

### ISSUE THREAD

**Issue by blyxxyz** [httpie/httpie#1263]
## Checklist

- [x] I've searched for similar issues.
- [x] I'm using the latest version of HTTPie.

---

## Minimal reproduction code and steps

Run `http --offline --json post :`

## Current result

A request with `Content-Type: application/json` and an empty body is sent.

## Expected result

`{}` is sent as a body.

---

It seems to me that HTTPie shouldn't construct an invalid JSON body if it picks a JSON content type.

(Without the `--json` flag no `Content-Type` header is sent, so everything's fine.)

See also:
- ducaale/xh#218
- #137

**Comment by isidentical** [comment]
Thanks for the report @blyxxyz, but we have concluded that this might not be very intuitive (adding a different behavior when a default option is specified explicitly). I think the easiest route is just sending it with `--raw`, e.g `http --offline pie.dev/get --raw="{}"`.

**Comment by blyxxyz** [comment]
#137 already decided opposite by making explicit `--json` add a `Content-Type` header, so then maybe that should be reverted instead? Right now it's inconsistent.
