### ISSUE TITLE
httpie could not request multiple url

### ISSUE THREAD

**Issue by binbjz** [httpie/httpie#1290]
## Checklist

- [x] I've searched for similar issues.
- [x] I'm using the latest version of HTTPie.

---
## I have several questions
1. httpie could not request for multiple url
2. Whether httpie supports HTTP/2 or HTTP/3
3. Why can the output response headers use so many options (--hea, --head, --header, --headers)

---
## Minimal reproduction code and steps

1. https www.python.org --header
HTTP/1.1 200 OK
Accept-Ranges: bytes
Age: 148
Connection: keep-alive
Content-Length: 49696
Content-Type: text/html; charset=utf-8
Date: Wed, 02 Feb 2022 15:10:14 GMT
Server: nginx
Strict-Transport-Security: max-age=63072000; includeSubDomains
Vary: Cookie
Via: 1.1 vegur, 1.1 varnish, 1.1 varnish
X-Cache: HIT, HIT
X-Cache-Hits: 3, 42
X-Frame-Options: DENY
X-Served-By: cache-iad-kcgs7200116-IAD, cache-hnd18721-HND
X-Timer: S1643814614.230216,VS0,VE0

2. curl -i -H "Accept: application/json" -H "Content-Type: application/json" www.python.org python.org
HTTP/1.1 301 Moved Permanently
Server: Varnish
Retry-After: 0
Location: https://www.python.org/
Content-Length: 0
Accept-Ranges: bytes
Date: Wed, 02 Feb 2022 15:09:21 GMT
Via: 1.1 varnish
Connection: close
X-Served-By: cache-hnd18741-HND
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1643814562.757519,VS0,VE0
Strict-Transport-Security: max-age=63072000; includeSubDomains

    HTTP/1.1 301 Moved Permanently
    Content-length: 0
    Location: https://python.org/

3. https --header www.python.org python.org
usage: http [--json] [--form] [--multipart] [--boundary BOUNDARY] [--raw RAW] [--compress] [--pretty {all,colors,format,none}] [--style STYLE] [--unsorted] [--sorted] [--response-charset ENCODING]
            [--response-mime MIME_TYPE] [--format-options FORMAT_OPTIONS] [--print WHAT] [--headers] [--meta] [--body] [--verbose] [--all] [--history-print WHAT] [--stream] [--output FILE] [--download]
            [--continue] [--quiet] [--session SESSION_NAME_OR_PATH | --session-read-only SESSION_NAME_OR_PATH] [--auth USER[:PASS] | TOKEN] [--auth-type {basic,bearer,digest}] [--ignore-netrc] [--offline]
            [--proxy PROTOCOL:PROXY_URL] [--follow] [--max-redirects MAX_REDIRECTS] [--max-headers MAX_HEADERS] [--timeout SECONDS] [--check-status] [--path-as-is] [--chunked] [--verify VERIFY]
            [--ssl {ssl2.3,tls1,tls1.1,tls1.2}] [--ciphers CIPHERS] [--cert CERT] [--cert-key CERT_KEY] [--ignore-stdin] [--help] [--version] [--traceback] [--default-scheme DEFAULT_SCHEME] [--debug]
            [METHOD] URL [REQUEST_ITEM ...]
http: error: 'python.org' is not a valid value

## Current result
http: error: 'python.org' is not a valid value
…

## Expected result
Get multiple url headers
…

---

## Debug output

Please re-run the command with `--debug`, then copy the entire command & output and paste both below:

```bash
$ http --debug <COMPLETE ARGUMENT LIST THAT TRIGGERS THE ERROR>
HTTPie 3.0.2
Requests 2.27.1
Pygments 2.11.2
Python 3.10.1 (main, Dec  6 2021, 22:18:13) [Clang 13.0.0 (clang-1300.0.29.3)]
/opt/homebrew/Cellar/httpie/3.0.2/libexec/bin/python3.10
Darwin 21.2.0

<Environment {'as_silent': <function Environment.as_silent at 0x101af4040>,
 'colors': 256,
 'config': {'default_options': []},
 'config_dir': PosixPath('/Users/zhaobin/.config/httpie'),
 'devnull': <property object at 0x101ad36f0>,
 'is_windows': False,
 'log_error': <function Environment.log_error at 0x101af40d0>,
 'program_name': 'https',
 'stderr': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'stderr_isatty': True,
 'stdin': <_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'>,
 'stdin_encoding': 'utf-8',
 'stdin_isatty': True,
 'stdout': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>,
 'stdout_encoding': 'utf-8',
 'stdout_isatty': True}>

<PluginManager {'adapters': [],
 'auth': [<class 'httpie.plugins.builtin.BasicAuthPlugin'>,
          <class 'httpie.plugins.builtin.DigestAuthPlugin'>,
          <class 'httpie.plugins.builtin.BearerAuthPlugin'>],
 'converters': [],
 'formatters': [<class 'httpie.output.formatters.headers.HeadersFormatter'>,
                <class 'httpie.output.formatters.json.JSONFormatter'>,
                <class 'httpie.output.formatters.xml.XMLFormatter'>,
                <class 'httpie.output.formatters.colors.ColorFormatter'>]}>
Traceback (most recent call last):
  File "/opt/homebrew/bin/https", line 33, in <module>
    sys.exit(load_entry_point('httpie==3.0.2', 'console_scripts', 'https')())
  File "/opt/homebrew/Cellar/httpie/3.0.2/libexec/lib/python3.10/site-packages/httpie/__main__.py", line 9, in main
    exit_status = main()
  File "/opt/homebrew/Cellar/httpie/3.0.2/libexec/lib/python3.10/site-packages/httpie/core.py", line 154, in main
    return raw_main(
  File "/opt/homebrew/Cellar/httpie/3.0.2/libexec/lib/python3.10/site-packages/httpie/core.py", line 70, in raw_main
    parsed_args = parser.parse_args(
  File "/opt/homebrew/Cellar/httpie/3.0.2/libexec/lib/python3.10/site-packages/httpie/cli/argparser.py", line 147, in parse_args
    self._guess_method()
  File "/opt/homebrew/Cellar/httpie/3.0.2/libexec/lib/python3.10/site-packages/httpie/cli/argparser.py", line 384, in _guess_method
    *SEPARATOR_GROUP_ALL_ITEMS).__call__(self.args.url))
  File "/opt/homebrew/Cellar/httpie/3.0.2/libexec/lib/python3.10/site-packages/httpie/cli/argtypes.py", line 106, in __call__
    raise argparse.ArgumentTypeError(f'{s!r} is not a valid value')
argparse.ArgumentTypeError: 'python.org' is not a valid value
```

## Additional information, screenshots, or code examples

…

**Comment by isidentical** [comment]
Hey @binbjz, unlike `cURL` we do not support sending multiple requests to multiple urls in the same run. You would have to run `http` command twice with different inputs.
