### ISSUE TITLE
Slow startup on Windows

### ISSUE THREAD

**Issue by mkmoisen** [httpie/httpie#1298]
The HTTPie client for me on Windows is pretty slow. It takes about 2-3 seconds before the request is launched.

Does anyone know what the reason is?

Could this be optimized?

**Comment by isidentical** [comment]
Hey @mkmoisen, I am not sure about windows but locally it takes around 150 ms (0.15 seconds) to fire up a new offline request. Plus the time spent on networking, it roughly adds up to 300 ms. Would you mind benchmarking `http --offline pie.dev/get` to get realiable results?

I'll also try to benchmark it on windows (though since Ill be use a virtual machine to do that, it might not be really reliable).

**Comment by mkmoisen** [comment]
Hi @isidentical,

Running `http --offline pie.dev/get` results in the same 2-3 second wait before I see results on my screen. If I use curl (From the Windows linux subsystem) it feels pretty much instant.

It seems to me that the http client simply takes 2-3 seconds to load up, before it actually launches a request. I think the request itself is fast. For example in my case, I am using httpie to hit my application on localhost, so there is no network impact.

**Comment by isidentical** [comment]
With the latest HTTPie from the choco, I can achieve a `0.4` seconds runtime per request on a virtual machine with Windows 11:
![image](https://user-images.githubusercontent.com/47358913/155082026-98611051-e2bb-4fa2-9954-dcf29aa7bdab.png)

Would you mind sharing your system configuration @mkmoisen (the full OS version, python version if applicable, HTTPie version)?

**Comment by mkmoisen** [comment]
Here is httpie, about 1.5 seconds:

![image](https://user-images.githubusercontent.com/2534631/155209587-c9af12fd-e05f-4303-bad6-7a533f991399.png)

Here is using curl, about 0.5 seconds:

![image](https://user-images.githubusercontent.com/2534631/155210332-018050bb-0cd6-4251-981e-15764a4d7922.png)

Would you be able to try using curl or some other non-http app?

I am using httpie 2.6.0 from Python 3.6.5.

![image](https://user-images.githubusercontent.com/2534631/155210489-36072120-c02e-49d8-83b4-62eadd24ff69.png)

I use Windows 10 Enterprise, Version 20H2

**Comment by isidentical** [comment]
Would you mind upgrading to 3.0 and test it again?

**Comment by mkmoisen** [comment]
When I do `pip install httpie --upgrade` it says:

> Requirement already up-to-date: httpie in c:\python36\lib\site-packages (2.6.0)

How do I upgrade to 3.0?

**Comment by isidentical** [comment]
@mkmoisen We've dropped support for python 3.6<, so I'd recommend you to install Python 3.10 and then try `pip install --upgrade --force httpie`.

**Comment by mkmoisen** [comment]
@isidentical I have a Python 3.9.5. After installing httpie on 3.9.5, It now takes between 0.6 and 0.8 seconds. Thank you!

> We've dropped support for python 3.6<

Do you men you dropped support for <3.7? The python version I originally installed httpie was 3.6.5.

**Comment by isidentical** [comment]
> Do you mean you dropped support for <3.7? The python version I originally installed httpie was 3.6.5.

Yes, sorry for the confusion.

> @isidentical I have a Python 3.9.5. After installing httpie 3.0.2 on python 3.9.5, It now takes between 0.6 and 0.8 seconds. Thank you!


Glad that upgrading worked for you! Please let us know if you experience any other issue.
