### ISSUE TITLE
--offline not being recognized

### ISSUE THREAD

**Issue by igoracmelo** [httpie/httpie#1299]
## Checklist

- [X] I've searched for similar issues.
- [X] I'm using the latest version of HTTPie.

---

OS: Ubuntu 20.04 LTS

## Minimal reproduction code and steps

1. `pip3 install httpie`
2. `http google.com --offline`

## Current result
`http: error: unrecognized arguments: --offline`

…

## Expected result
![image](https://user-images.githubusercontent.com/85039990/153973773-1d988f09-a677-44db-b325-5bc3bc15885b.png)

https://httpie.io/docs/cli/introduction
…

---

## Debug output

Please re-run the command with `--debug`, then copy the entire command & output and paste both below:

```bash
HTTPie 1.0.3
Requests 2.22.0
Pygments 2.3.1
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]
/usr/bin/python3
Linux 5.13.0-28-generic

<Environment {
    "colors": 256,
    "config": {
        "__meta__": {
            "about": "HTTPie configuration file",
            "help": "https://httpie.org/doc#config",
            "httpie": "1.0.3"
        },
        "default_options": "[]"
    },
    "config_dir": "/home/igor/.httpie",
    "is_windows": false,
    "stderr": "<_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>",
    "stderr_isatty": true,
    "stdin": "<_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'>",
    "stdin_encoding": "utf-8",
    "stdin_isatty": true,
    "stdout": "<_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>",
    "stdout_encoding": "utf-8",
    "stdout_isatty": true
}>
usage: http [--json] [--form] [--pretty {all,colors,format,none}] [--style STYLE] [--print WHAT] [--headers] [--body] [--verbose] [--all]
            [--history-print WHAT] [--stream] [--output FILE] [--download] [--continue]
            [--session SESSION_NAME_OR_PATH | --session-read-only SESSION_NAME_OR_PATH] [--auth USER[:PASS]] [--auth-type {basic,digest}]
            [--proxy PROTOCOL:PROXY_URL] [--follow] [--max-redirects MAX_REDIRECTS] [--timeout SECONDS] [--check-status] [--verify VERIFY]
            [--ssl {ssl2.3,tls1,tls1.1,tls1.2}] [--cert CERT] [--cert-key CERT_KEY] [--ignore-stdin] [--help] [--version] [--traceback]
            [--default-scheme DEFAULT_SCHEME] [--debug]
            [METHOD] URL [REQUEST_ITEM [REQUEST_ITEM ...]]
http: error: unrecognized arguments: --offline
```

## Additional information, screenshots, or code examples
https://httpie.io/docs/cli/introduction
…

**Comment by isidentical** [comment]
Hey @igoracmelo! The HTTPie command accepts our request data syntax after the URL. That is the reason you can't pass it. The correct way should be:
```
$ http --offline google.com
```

**Comment by ko2in** [comment]
As the error in the console clearly says the ```--offline``` argument is no longer recognized. I'm not sure why this issue was closed.

![Screenshot from 2022-08-04 17-58-35](https://user-images.githubusercontent.com/930315/182836370-d3d157a6-c4e7-4dcb-8e89-de59365b5f42.png)

**Comment by jakubroztocil** [comment]
@ko2in this looks like an antient version of HTTPie. I recommend upgrading to the latest version (https://httpie.io/docs/cli/installation).

**Comment by ko2in** [comment]
@jakubroztocil Thanks. I installed via ```snap```. I've tried ```snap refresh httpie``` but it says no updates available.

![Screenshot from 2022-08-04 18-09-36](https://user-images.githubusercontent.com/930315/182838241-5ca1ef8c-e141-4c7c-bff1-0aade82fe3c7.png)

**Comment by jakubroztocil** [comment]
@ko2in what does `http --version` say?

**Comment by ko2in** [comment]
The version is 1.0.3.

![Screenshot from 2022-08-04 18-20-33](https://user-images.githubusercontent.com/930315/182841454-f5e0a5b3-5d97-494f-a239-20cfc19ad282.png)

**Comment by ko2in** [comment]
@jakubroztocil I've checked the snap and the httpie version is 3.2.1.

![Screenshot from 2022-08-04 19-32-57](https://user-images.githubusercontent.com/930315/182853977-cbe699aa-6f95-4fcb-b1b8-637b7b67da18.png)

And ```https --version``` also returns the same version and the ```--offline``` argument works with ```https``` command.

![Screenshot from 2022-08-04 19-35-31](https://user-images.githubusercontent.com/930315/182854123-de98e7de-5033-4fd6-8700-d9ff1e2f13ff.png)

**Comment by jakubroztocil** [comment]
@ko2in you may have the `1.0.3` version installed using another method (e.g., `pip` or `apt`). So if you uninstall it (and reinstall the newer snap, if needed), you should be good.

**Comment by ko2in** [comment]
@jakubroztocil You're right. I've also httpie installed with apt. I uninstall from apt and now it works. Thanks.
