### ISSUE TITLE
Feature request: scroll persistence between tabs

### ISSUE THREAD

**Issue by shoyip** [httpie/httpie#1367]
## Checklist

- [x] I've searched for similar feature requests.

---

## Enhancement request

I would like Httpie to have persistance of scroll position while switching between tabs.

---

## Problem it solves

This feature will enable the user to visually compare bits of response previews or requests between different tabs.

---

**Comment by jakubroztocil** [comment]
Thanks, @shoyip — we’ll look into it (also remembering the cursor position).

**Comment by jakubroztocil** [comment]
Btw, this is the HTTPie for Terminal repo. For Desktop, please report issues here: https://github.com/httpie/desktop

(I’m closing this, but we will still ping you when the feature has been implemented. Feel free to cross-post it there.)
