### ISSUE TITLE
Failing test cases while setup

### ISSUE THREAD

**Issue by nishantsikarwar** [httpie/httpie#1467]
## Checklist

- [x] I've searched for similar issues.
- [x] I'm using the latest version of HTTPie.

---

## Minimal reproduction code and steps

1. gh repo clone httpie/httpie (in codespaces)
2. make install
3. make test-cover

## Current result
282 failed, 736 passed, 4 skipped, 3 xfailed, 1 xpassed, 352 warnings in 125.12s (0:02:05) ==================================================
make: *** [Makefile:107: test] Error 1
…

## Expected result

all test cases should pass successfully on the master branch

…

---

## Debug output

Please re-run the command with `--debug`, then copy the entire command & output and paste both below:

```bash
$ http --debug <COMPLETE ARGUMENT LIST THAT TRIGGERS THE ERROR>
<COMPLETE OUTPUT>
```

## Additional information, screenshots, or code examples

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/23703632/210701207-9d8d19be-a7cc-4819-b53f-0df91ce64384.png">

…

**Comment by nishantsikarwar** [comment]
@jakubroztocil 

can you pls help me on the subject 

Best Regards,
Nishant

**Comment by Chukwudum12** [comment]
How which subject do you want

**Comment by nishantsikarwar** [comment]
@Chukwudum12 

I meant the setup is failing in codespaces with the instruction mentioned in the README,  I have described above.
can you help in fixing the setup?

best Regards,
Nishant

**Comment by nishantsikarwar** [comment]
> Yes, I can help.
> […](#)

@Chukwudum12, can you check the above steps i followed and tell me where i made the mistake or what the issue is exaclty 

Best Regards,
Nishant.

**Comment by nishantsikarwar** [comment]
@Chukwudum12 and @jakubroztocil can you help on the setup pls 

best regards,
Nishant

**Comment by Chukwudum12** [comment]
Yes, I can.

**Comment by nishantsikarwar** [comment]
@Chukwudum12 | @jakubroztocil 
 can you pls describe the steps to setup the project or tell me the mistake in the above steps that I might be making 


best regards,
Nishant
