### ISSUE TITLE
IPv6 addresses

### ISSUE THREAD

**Issue by ghost** [httpie/httpie#155]
I'm able to `http -h 173.194.33.34` and get a valid response, but using `http -h 2607:f8b0:400a:801::100e` produces the following for me:

```
http: error: LocationParseError: Failed to parse: Failed to parse: 2607:f8b0:400a:801::100e
```

It would seem that httpie doesn't support direct IPv6 address input as `http -h ipv6.google.com` works fine.

**Comment by sigmavirus24** [comment]
@jkbrzt this should be close-able now.

**Comment by faheel** [comment]
@sigmavirus24 Nope, the issue still exists in HTTPie v2.0.0:

```
$ http 2606:4700::6812:748

http: error: InvalidURL: Failed to parse: http://2606:4700::6812:748
```

**Comment by sigmavirus24** [comment]
@faheel the Requests bug was resolved, it seems there's some other bug is at play the URL constructed. The _correct_ URL is `http://[2606:4700::6812:748]`

**Comment by faheel** [comment]
@sigmavirus24 Thanks! I didn't know that's how IPv6 addresses need to be written in URLs.

**Comment by Almad** [comment]
The request bug is fixed and this works now 🎉
