### ISSUE TITLE
Generic plugin API (for output processors and such)

### ISSUE THREAD

**Issue by jakubroztocil** [httpie/httpie#177]
Add a more generic plugin API that would allow adding new output processors. 

(There already is an API for [auth plugins](https://github.com/jkbr/httpie/blob/master/httpie/plugins/manager.py)).
#### Candidates / use cases
- [x] msgpack support #284 
- [x] http over unix domain sockets #209
- [ ] Akamai debugging https://github.com/jakubroztocil/httpie/compare/master...matteck:master
- [ ] WebSocket #371
- [ ] triggering action upon receiving specific header #369

**Comment by Almad** [comment]
There is now a way to define auth, formatter, convertor and transport plugin. [See "documentation" in the code. ](https://github.com/httpie/httpie/blob/master/httpie/plugins/base.py)

The API is not considered stable, thus not publicly documented. I am closing this issue as it's "good enough" for now, but feedback on the API is welcome here!
