### ISSUE TITLE
Add Python API support

### ISSUE THREAD

**Issue by giampaolo** [httpie/httpie#205]
httpie is a very cool CLI tool, far better than curl.
It would be great if there would a minimal documented API support so that it can also be used as a Python module you can import and make requests with.
The way I would expect it to work might be something like this:

```
>>> from httpie import interpret_args
>>> resp = interpret_args("http GET http://localhost:8000/help")
>>> resp
<Response [200]>
>>> resp.status_code
200
>>> 
```

Thoughts?

**Comment by felipevolpone** [comment]
I think that I could start the process to create an abstraction layer to provide httpie as an API. There is some task already in course to do this?

**Comment by ryneeverett** [comment]
Here's another use case I ran into in the wild: [calling httpie in a subprocess just for the pretty printing and logging](https://github.com/Valloric/ycmd/blob/81884b3/examples/example_client.py#L236-L256).

**Comment by Almad** [comment]
This is a duplicate to #551—let's use that one as a canonical issue.
