### ISSUE TITLE
Response time

### ISSUE THREAD

**Issue by whodidthis** [httpie/httpie#243]
Could be handy to see a requests response time in verbose or with some other flag.

**Comment by guilleferrer** [comment]
+1

**Comment by PavloVasylchenko** [comment]
+1

**Comment by matrixise** [comment]
+1

**Comment by bgalek** [comment]
+1

**Comment by RyanDhuse** [comment]
+1

**Comment by exegete46** [comment]
+1

**Comment by ravshansbox** [comment]
+1

**Comment by asychev** [comment]
+1

**Comment by gblmarquez** [comment]
👍

**Comment by nowtvicebergteam** [comment]
👍

**Comment by heyalexej** [comment]
+1

**Comment by oleggromov** [comment]
I'd like to have response time too! 👍

**Comment by aum12** [comment]
+1

**Comment by qoomon** [comment]
+1

**Comment by postmeridiem** [comment]
+1

**Comment by ahbruinsma** [comment]
+1

**Comment by Evlos** [comment]
+1

**Comment by kusha** [comment]
+1

**Comment by davegallant** [comment]
+2

**Comment by tmhpfnr** [comment]
+1

**Comment by sahas-** [comment]
+1

**Comment by andreafalzetti** [comment]
+1

**Comment by bytedaring** [comment]
+1

**Comment by bytedaring** [comment]
👍

**Comment by lcd1232** [comment]
👍

**Comment by stellarpower** [comment]
For anyone looking for a quick hack that may get the job done, the bonus is that I learned today about the `time` command in Fish (and possibly your other favourite shell, I believe the bash has it)

**Comment by ramilmsh** [comment]
> For anyone looking for a quick hack that may get the job done, the bonus is that I learned today about the `time` command in Fish (and possibly your other favourite shell, I believe the bash has it)

JFYI, this will time the command, not request, meaning parsing the arguments, making the request, compression, parsing response and so on will be included. It's fine, if your request time much larger (orders of magnitude) than any local operations that need to be performed, but something you need to keep an eye out for

**Comment by jakubroztocil** [comment]
🎉 This feature is now publicly available in [HTTPie for Terminal 3.0](https://httpie.io/blog/httpie-3.0.0): 

👉 https://httpie.io/docs/cli/response-meta
