### ISSUE TITLE
add time option

### ISSUE THREAD

**Issue by beepony** [httpie/httpie#258]
could you consider to add time option like cURL?
eg:
![2014-09-19 4 52 14](https://cloud.githubusercontent.com/assets/7813288/4332940/5a7741ec-3fda-11e4-8aa6-44239bfa6c0e.png)

**Comment by hjacobs** [comment]
:+1:  for the timing option

**Comment by sigmavirus24** [comment]
So this is a bit different, we can't really offer `%{time_connect}:%{time_starttransfer}` we can give the time form when we sent the request to the time to the first byte received. Requests has no intention of really changing what it offers in this area since `elapsed` covers 98% of our users.

**Comment by vbvyas** [comment]
👍 Just having total time like postman does is good for most users

**Comment by jakubroztocil** [comment]
Canonical issue: #243
