### ISSUE TITLE
Odd ASCII characters in response

### ISSUE THREAD

**Issue by SamuelMarks** [httpie/httpie#313]
```
E:\>http HEAD :5555/api/signup
←[38;5;202;01mHTTP←[39;00m←[38;5;15m/←[39m←[38;5;33;01m1.0←[39;00m←[38;5;15m ←[3
9m←[38;5;33;01m404←[39;00m←[38;5;15m ←[39m←[38;5;15mNot Found←[39m
←[38;5;198;01mContent-Length←[39;00m←[38;5;15m:←[39m←[38;5;15m ←[39m←[38;5;32m74
0←[39m
←[38;5;198;01mContent-Type←[39;00m←[38;5;15m:←[39m←[38;5;15m ←[39m←[38;5;32mtext
/html; charset=UTF-8←[39m
←[38;5;198;01mDate←[39;00m←[38;5;15m:←[39m←[38;5;15m ←[39m←[38;5;32mSun, 15 Feb
2015 21:28:42 GMT←[39m
←[38;5;198;01mServer←[39;00m←[38;5;15m:←[39m←[38;5;15m ←[39m←[38;5;32mWSGIServer
/0.1 Python/2.7.9←[39m←[0m

←[0m←[0m

←[0m
```

Similar appears `←[0` on just running `http` without args. My cmd is using a Unicode font, and has clink (GNU Readline port) installed.

**Is there some property I can set to make this work like its Linux equivalent?**

EDIT: Trying with ConEmu cmd wrapper and everything works. Still would like this to work in regular cmd…

**Comment by jakubroztocil** [comment]
It's supposed to work even in regular `cmd.exe` – [Colorama](https://pypi.python.org/pypi/colorama) is used for that. But for some reason it doesn't to the conversion for you. What output does `http --debug` give you?

**Comment by SamuelMarks** [comment]
```
E:\Projects>http :8000 --debug
HTTPie 0.9.1
HTTPie data: C:\Users\Samuel\AppData\Roaming\\httpie
Requests 2.5.1
Pygments 2.0.2
Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] win32

>>> requests.request({'allow_redirects': False,
 'auth': None,
 'cert': None,
 'data': OrderedDict(),
 'files': DataDict(),
 'headers': {'User-Agent': 'HTTPie/0.9.1'},
 'method': 'get',
 'params': ParamsDict(),
 'proxies': {},
 'stream': True,
 'timeout': 30,
 'url': u'http://localhost:8000',
 'verify': True})
```

**Comment by TuulaP** [comment]
Saw also this directly after installing with httpie. However, in a [colorama bug](https://github.com/tartley/colorama/issues/48#issue-68769761), it is hinted that just unsetting the TERM variable `set TERM=`  can solve this. (At least worked for me for cmd & Console2 with httpie 0.9.2, requests 2.7.0, pygments 2.0.2 & python 2.7.10).

**Comment by SamuelMarks** [comment]
Thanks, that did the trick. I know it'll be a hack, but do we just want to pass through that setting somewhere in httpie?

I'd be happy to find the place and make the patch, but don't want to do that if we don't get a merge out of it.

**Comment by SamuelMarks** [comment]
Darn, this solution stopped working as of v0.9.2 :-1:

**Comment by Almad** [comment]
Seems to be solved by upstream. Please let us know if it isn't!
