### ISSUE TITLE
"default" netrc authorization results in "403 Forbidden" errors

### ISSUE THREAD

**Issue by proinsias** [httpie/httpie#464]
I have a suggestion to at least edit the readme file to alert users of a confusing "403 Forbidden" error, if not update httpie to include relevant hints in the `--debug` output.

While trying to debug my [bashhub](https://bashhub.com/) installation, I tried the following command suggested by the author:

`http --debug https://bashhub.com/api/v1/system?mac=181219917565350 "Authorization:Bearer $BH_AUTH"`

and got the following output:

```
HTTPie 0.9.3
HTTPie data: /Users/ftod/.httpie
Requests 2.9.1
Pygments 2.0.2
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] darwin

>>> requests.request(**{'allow_redirects': False,
 'auth': None,
 'cert': None,
 'data': OrderedDict(),
 'files': DataDict(),
 'headers': {u'Authorization': 'Bearer <redacted>',
             'User-Agent': 'HTTPie/0.9.3'},
 'method': 'get',
 'params': ParamsDict(),
 'proxies': {},
 'stream': True,
 'timeout': 30,
 'url': u'https://bashhub.com/api/v1/system?mac=181219917565350',
 'verify': True})

HTTP/1.1 403 Forbidden
Connection: keep-alive
Content-Length: 0
Date: Sat, 23 Apr 2016 02:34:09 GMT
Server: nginx
Via: 1.1 vegur
```

I investigated using the suggestions from #139:

`python -m netrc`

and got the following output:

```
machine default
    login 'anonymous'
    password 'francis.odonovan@gmail.com'
```

That's when I realized that httpie was trying to connect using this old `default` login that I have for `ftp` clients, rather than the authentication token I had given it. 

I'm suggesting that the readme file be updated to warn users of this confusing situation, and/or that httpie be updated to include information used from the .netrc file in the `--debug` output. I'm happy to do the former, and could take a crack at the latter.

**Comment by sigmavirus24** [comment]
I'm rather certain that httpie doesn't do any netrc integration itself. I believe it leaves discovery/handling of netrcs to [requests](/kennethreitz/requests). To include this information in httpie's debug information you'll have to add a bit of code to see if requests is going to use netrc at all and then print that out with the rest of the debug info. I don't know if @jkbrzt will want that kind of logic
