### ISSUE TITLE
url with gbk encode report UnicodeDecodeError

### ISSUE THREAD

**Issue by rogerdehe** [httpie/httpie#578]
I have an API which use `gbk` encode, I have to call like this:

    echo http://10.202.15.197:20176?user_id=1&query_type=GEOSPLIT&address=广东省深圳市宝安&ret_splitinfo=1 | iconv -f utf-8 -t gbk | xargs curl | iconv -f gbk -t utf-8

but if I change `cURL` to `httpie` it will report :

    Traceback (most recent call last):
      File "/usr/bin/http", line 11, in <module>
        load_entry_point('httpie==0.9.8', 'console_scripts', 'http')()
      File "/usr/lib/python2.7/dist-packages/httpie/__main__.py", line 11, in main
        sys.exit(main())
      File "/usr/lib/python2.7/dist-packages/httpie/core.py", line 182, in main
        args = decode_args(args, env.stdin_encoding)
      File "/usr/lib/python2.7/dist-packages/httpie/core.py", line 71, in decode_args
        for arg in args
      File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
        return codecs.utf_8_decode(input, errors, True)
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xb9 in position 65: invalid start byte

**Comment by GotoCode** [comment]
Is it possible that the arguments to `iconv` have been supplied in reverse?

From what I understand, since the URL uses the `GBK` encoding, I believe this part of your code: 
```
... | iconv -f utf-8 -t gbk | xargs http | iconv -f gbk -t utf-8
```

...should actually be written as: 
```
... | iconv -f gbk -t utf-8 | xargs http | iconv -f utf-8 -t gbk
```

**Comment by BoboTiG** [comment]
I think @GotoCode has found the issue and fix :pie: 

Please feel free to reopen this if you still have the issue/questions.
