### ISSUE TITLE
URL parameters from file

### ISSUE THREAD

**Issue by seguri** [httpie/httpie#605]
Hello,

I would like the syntax `==@` to add an URL parameter from file.

I'm currently doing that with `http ... key==$(<apikey)`.

I hope nobody asked this before, I've searched among issues and documentation.

**Comment by jassi-bhullar** [comment]
This is a test comment

**Comment by jassi-bhullar** [comment]
HTTPie is awesome :)

**Comment by chrisngyn** [comment]
@YKo20010 and I will be working on this issue.

**Comment by seguri** [comment]
@jakubroztocil Hi, I've received a GitHub notification that you and @YKo20010 are going to work on this, is that true?

**Comment by chrisngyn** [comment]
@seguri hi - after discussing with Jakub we've decided to revisit this topic later, sorry about the notif!
