### ISSUE TITLE
Feature Request: more user friendly message for download time elapsed

### ISSUE THREAD

**Issue by hanxue** [httpie/httpie#699]
When a `--download` operation takes a long time, the output will be 

`Done. 51.05 MB in 1653.26288s `

When the number of seconds is in the thousands, it requires more effort to calculate how many minutes of hours elapsed for the download operationg. 

A full example:

```
$ http --download http://dl.caffe.berkeleyvision.org/bvlc_googlenet.caffemodel
HTTP/1.1 200 OK
Accept-Ranges: bytes
Connection: keep-alive
Content-Length: 53533754
Content-Type: application/octet-stream
Date: Mon, 03 Sep 2018 07:23:08 GMT
ETag: "54934a20-330dc3a"
Last-Modified: Thu, 18 Dec 2014 21:41:52 GMT
Server: nginx/1.4.6 (Ubuntu)

Downloading 51.05 MB to "bvlc_googlenet.caffemodel-1"
Done. 51.05 MB in 1653.26288s (31.62 kB/s)
```

The output could be more user friendly in this format:

```
Done. 51.05 MB in 27m 33.26s 
```

**Comment by tajbojc** [comment]
@isidentical it seems that this has been already solved:

**https://github.com/httpie/httpie/blob/master/httpie/output/ui/rich_progress.py#L48-L51**

Should this still be open?

**Comment by isidentical** [comment]
That is correct, thanks for noticing (my changes were isolated, and I didnt thought of this issue but it is nice that it also got solved through)
