### ISSUE TITLE
Chunked request body supported?

### ISSUE THREAD

**Issue by hongliang5316** [httpie/httpie#753]
Hello,
I want to test `http chunked request body`, did `httpie` support it?

**Comment by rocketraman** [comment]
I was looking for the same thing. I don't believe it does.

**Comment by shimmeris** [comment]
@jakubroztocil Hello, Can I work on this to add a feature to httpie so that it can post chunked encoding data?

**Comment by hongliang5316** [comment]
@shimmeris 
Hello, i think you can :)
