### ISSUE TITLE
Document JSON-escaping in "=" syntax

### ISSUE THREAD

**Issue by wataash** [httpie/httpie#813]
In `=` syntax, special characters:

- not a `char` defined in [RFC 8259](https://www.rfc-editor.org/rfc/rfc8259) 7. Strings
- non-ascii characters (such like "あ")

are escaped, and `:=` escapes only non-ascii characters:

```sh
http httpbin.org/post double_quote='"' non-ascii=あ new_line='
'
# sends: {"double_quote": "\"", "non-ascii": "\u3042", "new_line": "\n"}
```

![image](https://user-images.githubusercontent.com/4846670/213856464-e4733d38-64e7-4128-b000-ab976a95519e.png)

(The output of `http -v` is somewhat confusing, so I pasted a Wireshark capture. See https://github.com/httpie/httpie/issues/1474)

This behavior should be documented, shouldn't it?

**Comment by wataash** [comment]
I found a solution by using `:=`:

```hs
$ http -v httpbin.org/post foo:='"bar\nbaz"'
POST /post HTTP/1.1
...
User-Agent: HTTPie/1.0.3

{
    "foo": "bar\nbaz"
}

HTTP/1.1 200 OK
...
```

I keep this open to create a pull request related to this.

**Comment by zezenz** [comment]
Good

**Comment by t-mangoe** [comment]
What tasks remain in this issue?
If the documentation needs to be updated, where does it need to be updated?

**Comment by wataash** [comment]
Hi. I have not seen this issue in 3 years and things seem to have changed. Please wait a moment while I update it.

**Comment by wataash** [comment]
The description was not well written and was difficult to understand, sorry. I've updated it.

And now I have changed my mind, this is an intuitive specification, no document needed.
I'm closing this issue, thank you for looking it over!
