### ISSUE TITLE
More user-friendly curl-like output in case of error

### ISSUE THREAD

**Issue by zoulja** [httpie/httpie#815]
I really love HTTPie for the cases when everything works fine, but if HTTPie can't establish connection by some reason then I always have to switch back to curl to perform troubleshooting

Example:
`http: error: ConnectionError: HTTPSConnectionPool(host='myhost', port=32075): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x6fffed76630>: Failed to establish a new connection: [Errno 13] Permission denied')) while doing OPTIONS request to URL: https://myhost:32075/`

Whole error message displayed in one line with a lot of unclear diagnostics + Python's stacktrace.
Please make it more user-friendly/clear + modify formatting to improve readability
Thanks!

**Comment by juped** [comment]
@rch-liu and @ebonnecab will be working on this!

**Comment by jakubroztocil** [comment]
@juped @rch-liu @ebonnecab awesome!

I would start by manually triggering & identifying as many types of errors as possible (by connecting to non-existing servers, passing weird arguments, making requests while offline, …, be creative!).

For each error type for which it makes sense (for example, arguments errors are already handled by `argparse`), I‘d write a function that returns a useful string representation with enough context for the user. with these, I would create a mapping between each error type and the corresponding function.

Then, I‘d update the current catch-all handling to first try to get a custom representation for the given error from the mapping, and only if that fails, I‘d print out the exception like we do now.

https://github.com/jakubroztocil/httpie/blob/7ee519ef46ed0a4280f431d0c14745ed8244621f/httpie/core.py#L96-L109

The style and formatting of the errors should be consistent (between the new as well as the already existing errors). 

Each of the supported error types needs a test case:

https://github.com/jakubroztocil/httpie/blob/master/tests/test_errors.py

If anything, ask away!

**Comment by jakubroztocil** [comment]
Options that probably need to be taken into account: `--traceback` & `--debug`

**Comment by ebonnecab** [comment]
@jakubroztocil thank you for clarifying this issue for us! Can you further explain your last comment when you say those are two options to take into account?

**Comment by jakubroztocil** [comment]
@ebonnecab sure thing! These two flags have effect on how errors, etc., are displayed:

When there’s an exception, `--traceback` ensures a more verbose output. Compare the output of these two commands:

```bash
$ http nontfound.example.org
```

```bash
$ http --traceback nontfound.example.org
```

As for `--debug`, that adds some debug information about HTTPie and the request to the output:

```bash
$ http --debug
```

```bash
$ http --debug httpbin.org/get
```

I think you be changing their their behavior. You should just be aware of them, and test the new error handling also when the two options are used (individually and separately). To make sure it all still looks good. Does it make sense?

**Comment by ebonnecab** [comment]
Yes! @jakubroztocil that makes sense to me. Thank you!

**Comment by isidentical** [comment]
#1248 fixed some of the problems here. If you have other cases that are tricky to figure out in terms of error messages, please let us know. We are constantly looking forward to improve the UX of HTTPie.
