### ISSUE TITLE
Please add option to reformat XML body

### ISSUE THREAD

**Issue by Hubbitus** [httpie/httpie#825]
```
$ TERM=xterm-256color http http://localhost:8081/api/grid-service/GridInquiryService/GridInquiry @SOAP.realtime.xml
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 921
Content-Type: text/xml;charset=ISO-8859-1
Date: Sun, 29 Dec 2019 10:07:58 GMT

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns4:realtimeResponse xmlns:ns4="http://rdc.com/soap/GridInquiry" xmlns:ns3="http://rdc.com/soap" xmlns:ns2="http://service.rdc.com"><return><ns2:Status><ns2:StatusCode>0</ns2:StatusCode><ns2:Severity>INFO</ns2:Severity></ns2:Status><ns2:GridInquiryStatusRec><ns2:GridInquiryId>3380</ns2:GridInquiryId><ns2:GridInquiryStatus><ns2:GridInquiryStatusCode>COMPLETE</ns2:GridInquiryStatusCode></ns2:GridInquiryStatus></ns2:GridInquiryStatusRec><ns2:GridInquiryResultsRec><ns2:GridInquiryId>3380</ns2:GridInquiryId><ns2:GridInquiryStatus><ns2:GridInquiryStatusCode>COMPLETE</ns2:GridInquiryStatusCode></ns2:GridInquiryStatus><ns2:GridInquiryReviewStatus><ns2:GridInquiryReviewStatusCode>NOMATCH</ns2:GridInquiryReviewStatusCode></ns2:GridInquiryReviewStatus></ns2:GridInquiryResultsRec></return></ns4:realtimeResponse></soap:Body></soap:Envelope>
```
![image](https://user-images.githubusercontent.com/720349/71555361-6e96c380-2a3c-11ea-8952-02878e9928e8.png)

So output even colorized. But it lack of indentation structure. It will be very cool to see said `--reformat` option (f.e. like in [highlight](https://gitlab.com/saalen/highlight)).

**Comment by jakubroztocil** [comment]
I would love to have this, but  I‘m not aware of any decent formatter that would preserve namespaces, etc.  There have been a few naive attempts:

https://github.com/jakubroztocil/httpie/issues?q=xml+format.

**Comment by Hubbitus** [comment]
https://pypi.org/project/xmlformatter/
https://docs.python.org/3/library/xml.dom.minidom.html
https://lxml.de/tutorial.html all are not decent?

**Comment by JSamir** [comment]
SOAP/XML is still very much alive in the enterprise world. Maybe you can evaluate the suggestions from @Hubbitus ?

**Comment by BoboTiG** [comment]
We will reconsider the feature, but it is not a high priority for now. #720 seems quite straitforward, and if someone wants to give a hand, a good amount of tests are required to demonstrate old issues are not present (like https://github.com/httpie/httpie/pull/720#issuecomment-438920147).

I'll have a look in the future if nobody steps in.
