### ISSUE TITLE
yum install httpie - not working?

### ISSUE THREAD

**Issue by milapop** [httpie/httpie#851]
Help?

`# yum install httpie
CentOS-8 - AppStream                                                                                                         718 kB/s | 6.4 MB     00:09
CentOS-8 - Base                                                                                                              1.4 MB/s | 5.0 MB     00:03
CentOS-8 - Extras                                                                                                            2.3 kB/s | 2.1 kB     00:00
Extra Packages for Enterprise Linux 8 - x86_64                                                                               865 kB/s | 5.6 MB     00:06

No match for argument: httpie
`

**Comment by kclinden** [comment]
same

**Comment by jakubroztocil** [comment]
HTTPie for CentOS is _usually_ available in the [EPEL repo](https://fedoraproject.org/wiki/EPEL):


```bash
dnf install epel-release
dnf install httpie
```

If the HTTPie package hasn’t been updated for the latest CentOS (as it currently seems to be the case with CentOS 8), you can still [install HTTPie using pip](https://httpie.org/docs#windows-etc):

```bash
pip install httpie
```

**Comment by RishabhAgarwal-2001** [comment]
@jakubroztocil I want to update it in the docs.

**Comment by derick-webnettips-com** [comment]
installed using pip36 in my case works

**Comment by ani-sha** [comment]
Hi, @jakubroztocil is this problem fixed yet? I am unable to use `httpie` on RHEL 8. 

```
sudo yum install httpie 

No match for argument: httpie
Error: Unable to find a match: httpie

```

**Comment by johhnry** [comment]
Hi,

Same issue here on CentOS 8, can't install `httpie` using `yum`.

It should be mentioned in the docs!

**Comment by koresar** [comment]
This worked for me:

```
sudo pip3 install httpie
```

**Comment by markruler** [comment]
in my case (CentOS 7)

```bash
yum install httpie
# No package httpie available.

dnf
# -bash: dnf: command not found

pip
# -bash: pip: command not found

yum install epel-release
yum update
yum install httpie
# [...]
# Complete!
```

```bash
http --version
# 0.9.4
```

**Comment by BoboTiG** [comment]
The [documentation](https://httpie.io/docs) has been updated to reflect all commands needed. To summarize:

```bash
yum install epel-release
yum install httpie
```
