### ISSUE TITLE
Can order between JSON and files be controlled in multipart form?

### ISSUE THREAD

**Issue by msageryd** [httpie/httpie#903]
I'm wondering if the order between JSON fields and file attachments can be controlled. 

I need to test my api by having files come before JSON data in the stream. It seems that httpie always sends JSON first and then files.

**Comment by jakubroztocil** [comment]
Currently it's not possible but I'll see if something can be done about that.

**Comment by msageryd** [comment]
@jakubroztocil That would be awesome. This should be useful for everyone with my use case.

My use case:
- Receiving multipart form via email
- Attached files needs to be processed
- Email needs to be validated by checking field data

In some rare cases I'm receiving files before fields (I'm using Sendgrid mail parse). When this happens I need to buffer the files and wait for the fields in order to know what to know with the files.

It would be great to use httpie to test this edge case.

**Comment by ykdui** [comment]
Buy Valid Cvv CC Dumps Track 1/2 CC SSN DOB Track-1/2-FULLZ-Transfer/Western union Bank-Log-In-PayPal-Transfer-and-Log-In Buy/sell CVV CC DOB SSN FULLZ - Dumps Pin...
Telegram.@Ykidven

Cc Format Is
Format is:

Card Number | Exp. Date | CVV/CVV2 | First Name | Last Name | Street | City 
| State | Zip Code | Country | Phone | Type Of Card | Bank Name

I'm Loading All Types Of Paypal Account With No ChargeBacks... Cash app Loading I Can Load All Non Verified Account with No Problem Or Verified PayPal Account..I Even Sell Paypal Logs At Cheap Prices....Pm Me If You Interested In Loading Your Paypal Account
Telegram.@Ykidven

Paypal Transfer Price List
20$ for 250$
30$ for 350$
40$ for 400$
50$ for 500$
60$ for 600$
70$ for 700$
80$ for 800$
90$ for 950$
100$ for 1500$


CashApp Transfer Price List
20$ for 250$
30$ for 350$
40$ for 400$
50$ for 500$
60$ for 600$
70$ for 700$
80$ for 800$
90$ for 950$
100$ for 1500$
200$ for 3000$

Telegram@Ykidven

Doing Wu Transfers
I Am Doing Wu Transfer Here And I Need I Very Serious Buyer Who Also Want To Work With Me And Make Money With Me Here...
Note...i will Do The Transfer Then After you Track The Mtcn You Make Payment Before you have the sender's Info

Western Union Price List
30$ for 350$
40$ for 400$
50$ for 500$
60$ for 600$
70$ for 700$
80$ for 800$
90$ for 950$
100$ for 1500$
200$ for 2500$

Telegram.@Ykidven
Telegram.@Ykidven
Telegram.@Ykidven

ICQ...clarity.baron@bk.ru
ICQ...clarity.baron@bk.ru
ICQ...clarity.baron@bk.ru

**Comment by JJCCALDERON** [comment]
You can't

**Comment by jakubroztocil** [comment]
@msageryd HTTPie in `master` preserves the field ordering (will be included in v2.3.0).

**Comment by msageryd** [comment]
Wow, great work!


Sent from my iPhone

On 28 Sep 2020, at 13:55, Jakub Roztocil <notifications@github.com> wrote:

﻿

@msageryd<https://github.com/msageryd> HTTPie in master preserves the field ordering (will be included in v2.3.0).
