### ISSUE TITLE
Refactor client.py

### ISSUE THREAD

**Issue by gmelodie** [httpie/httpie#935]
Me and @kbanc were working on #932 and we found the `client.py` file a bit hard to go through and thought we could refactor it to look a bit like the `sessions.py`: there would be a `Client` class and all the logic for preparing and sending the requests would be done from this file.

The idea is pretty rough but @jakubroztocil if you have some thoughts we would really appreciate them!

**Comment by jakubroztocil** [comment]
@gmelodie  I’m all for cleanups & simplifying refactoring, so if you see some potential for that there, try to flesh something out, and can take a look at it. I cannot guarantee it will get merged, though.

**Comment by kbanc** [comment]
@jakubroztocil We've done some preliminary refactoring on the `client.py` file, and we've noticed that making it into a class may make the code more extensible, but we're not sure if that's a good idea.

Pros: readability, extensibility
Cons: May not be necessary - `collect_messages` is the only fn used from `client.py` and it's only called once in the codebase

If we were to make `client.py` into a `Client` class, do you have opinions on what state should be stored?

**Comment by isidentical** [comment]
Closing as per the notice in the linked PR.
