### ISSUE TITLE
request response time

### ISSUE THREAD

**Issue by s1ntaxe770r** [httpie/httpie#958]
I think it would be a good idea to have how long the response of a request took displayed in the output, this could be useful  if comparing API's or testing the performance impact of a change to an API. with a little help I'd be willing to help out with this

**Comment by jakubroztocil** [comment]
Canonical issue: #243

**Comment by isidentical** [comment]
🎉 This feature is now publicly available in [HTTPie for Terminal 3.0](https://httpie.io/blog/httpie-3.0.0): 

👉 https://httpie.io/docs/cli/response-meta
