### ISSUE TITLE
Pretty Print HTML Output (with newlines and indentation)?

### ISSUE THREAD

**Issue by ryanerwin** [httpie/httpie#959]
When printing `Content-type: application/json` httpie formats the json with newlines and indentation making it very easy to read.

<pre> <font color="#135CD0">❯</font> <font color="#328A5D">http</font> --body <font color="#FA701D">&apos;https://api2.nicehash.com/main/api/v2/legacy?method=stats.global.current&apos;</font>
{
    <font color="#135CD0"><b>&quot;method&quot;</b></font>: <font color="#FA701D">&quot;stats.global.current&quot;</font>,
    <font color="#135CD0"><b>&quot;result&quot;</b></font>: {
        <font color="#135CD0"><b>&quot;error&quot;</b></font>: <font color="#FA701D">&quot;Method not supported&quot;</font>
    }
}
</pre>

However, when returning text/html, the output is syntax highlighted but not reformatted with newlines and indentation. For short HTML pages, reformatting would make the results a lot more easily readable.

<pre> <font color="#135CD0">❯</font> <font color="#328A5D">http</font> --body google.com
&lt;<font color="#135CD0"><b>HTML</b></font>&gt;&lt;<font color="#135CD0"><b>HEAD</b></font>&gt;&lt;<font color="#135CD0"><b>meta</b></font> <font color="#33C3C1">http-equiv</font>=<font color="#FA701D">&quot;content-type&quot;</font> <font color="#33C3C1">content</font>=<font color="#FA701D">&quot;text/html;charset=utf-8&quot;</font>&gt;
&lt;<font color="#135CD0"><b>TITLE</b></font>&gt;301 Moved&lt;/<font color="#135CD0"><b>TITLE</b></font>&gt;&lt;/<font color="#135CD0"><b>HEAD</b></font>&gt;&lt;<font color="#135CD0"><b>BODY</b></font>&gt;
&lt;<font color="#135CD0"><b>H1</b></font>&gt;301 Moved&lt;/<font color="#135CD0"><b>H1</b></font>&gt;
The document has moved
&lt;<font color="#135CD0"><b>A</b></font> <font color="#33C3C1">HREF</font>=<font color="#FA701D">&quot;http://www.google.com/&quot;</font>&gt;here&lt;/<font color="#135CD0"><b>A</b></font>&gt;.
&lt;/<font color="#135CD0"><b>BODY</b></font>&gt;&lt;/<font color="#135CD0"><b>HTML</b></font>&gt;
</pre>

Syntax highlighting is fantastic, but would be very easy to read like:
```
<HTML>
   <HEAD>
      <meta http-equiv="content-type" content="text/html;charset=utf-8">
      <TITLE>301 Moved</TITLE>
   </HEAD>
   <BODY>
      <H1>301 Moved</H1>
      The document has moved
      <A HREF="http://www.google.com/">here</A>.
   </BODY>
</HTML>
```

**Comment by jakubroztocil** [comment]
@ryanerwin thanks for the suggestion. We used to have a XML/HTML formatter, but these languages is notoriously problematic in this regard and there’s no usable parser/formatter that we could plug in at this point. So I’m closing this for now.

**Comment by tobske** [comment]
@jakubroztocil Just a very vague idea: Could you maybe use prettier from https://prettier.io/ for this? I know that is commonly used in combination with editors but in the end it is just a npm module.

**Comment by BoboTiG** [comment]
@tobske, HTTPie is Python-based code, it would not make sens to install the whole NodeJS suite just to have HTML formatting.
We may rethink that part when we will know about a potential Python module that would solve the case.

**Comment by tobske** [comment]
Okay, I can understand that.

**Comment by martinszeltins** [comment]
I would also be interested in a formatter for html output, would make it so much easier to read.
