### ISSUE TITLE
[Docs] `cv@` & `=@` are getting replaced in docsite with [email-protected]

### ISSUE THREAD

**Issue by jskrzypek** [httpie/httpie#966]
![image (3)](https://user-images.githubusercontent.com/1513265/93520987-5b46c380-f8fd-11ea-8955-1f32519f5cbb.png)

Clicking on the link in `[email-protected]` takes me to https://httpie.org/cdn-cgi/l/email-protection

**Comment by jakubroztocil** [comment]
This should be fixed now. Thanks for the report, @jskrzypek!
