### ISSUE TITLE
Basic authentication: unexpected extra leading space in generated base64 token

### ISSUE THREAD

**Issue by maanuair** [httpie/httpie#971]
Hi,

I was giving `httpie` a try, in order to replace `curl` especially because of the session management.
And I might miss something, but I believe the Basic authentication token computed has an unexpected extra leading space.

**Steps to reproduce**
I run:
```
$ https --offline -a 'a:b' domain.tld/auth | grep Authorization
```
**Expected result**
- I get:
```
Authorization: Basic YTpi 
```
- Which, when decoded, gives:
```
$ echo \"$(printf "YTpi"|base64 -d)\"
"a:b"
```
**Actual result**
- I get:
```
Authorization: Basic wqBhOmI=
```
- Which, when decoded, gives an unexpected extra leading space:
```
$ echo \"$(printf "wqBhOmI="|base64 -d)\"
" a:b"
```
**Extra info**
- I checked the output given by `curl`, which gives the expected result: 
```
$ curl --verbose -u 'a:b' https://httpbin.org/auth 2>&1 | grep Authorization
> Authorization: Basic YTpi
```
- Debug output
```
$ https --debug --offline -a 'a:b' domain.tld/auth
HTTPie 2.2.0
Requests 2.24.0
Pygments 2.6.1
Python 3.8.5 (default, Jul 21 2020, 10:48:26)
[Clang 11.0.3 (clang-1103.0.32.62)]
/usr/local/Cellar/httpie/2.2.0/libexec/bin/python3.8
Darwin 19.6.0

<Environment {'colors': 256,
 'config': {'default_options': []},
 'config_dir': PosixPath('/Users/eroubion/.config/httpie'),
 'is_windows': False,
 'log_error': <function Environment.log_error at 0x1057450d0>,
 'program_name': 'https',
 'stderr': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'stderr_isatty': True,
 'stdin': <_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'>,
 'stdin_encoding': 'utf-8',
 'stdin_isatty': True,
 'stdout': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>,
 'stdout_encoding': 'utf-8',
 'stdout_isatty': True}>

>>> requests.request(**{'auth': <httpie.plugins.builtin.HTTPBasicAuth object at 0x105814520>,
 'data': RequestJSONDataDict(),
 'files': RequestFilesDict(),
 'headers': {'User-Agent': b'HTTPie/2.2.0'},
 'method': 'get',
 'params': RequestQueryParamsDict(),
 'url': 'https://domain.tld/auth'})

GET /auth HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Basic wqBhOmI=
Connection: keep-alive
Host: domain.tld
User-Agent: HTTPie/2.2.0
```

Of course, the header could be better parsed server-side: actually it just does not authenticate the request. Maybe it could be smarter (?), but seems weird to me.

As I said, I may miss something here, first experience with `httpie` here , and it looks "wow": thanks!

**Comment by jakubroztocil** [comment]
@maanuair thanks for the report! I don’t seem to be able to reproduce it:

```bash
$ https --offline -a 'a:b' domain.tld/auth | grep Authorization
Authorization: Basic YTpi
```

Even with the exact same versions of everything:

```bash
$ https --debug --offline -a 'a:b' domain.tld/auth
HTTPie 2.2.0
Requests 2.24.0
Pygments 2.6.1
Python 3.8.5 (default, Jul 21 2020, 10:48:26)
[Clang 11.0.3 (clang-1103.0.32.62)]
/usr/local/Cellar/httpie/2.2.0/libexec/bin/python3.8
Darwin 19.6.0

<Environment {'colors': 256,
 'config': {'default_options': ['--style=monokai']},
 'config_dir': PosixPath('/Users/jakub/.config/httpie'),
 'is_windows': False,
 'log_error': <function Environment.log_error at 0x10aa16ca0>,
 'program_name': 'http',
 'stderr': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'stderr_isatty': True,
 'stdin': <_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'>,
 'stdin_encoding': 'utf-8',
 'stdin_isatty': True,
 'stdout': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>,
 'stdout_encoding': 'utf-8',
 'stdout_isatty': True}>

>>> requests.request(**{'auth': <httpie.plugins.builtin.HTTPBasicAuth object at 0x10aaed610>,
 'data': RequestJSONDataDict(),
 'files': RequestFilesDict(),
 'headers': {'User-Agent': b'HTTPie/2.2.0'},
 'method': 'get',
 'params': RequestQueryParamsDict(),
 'url': 'https://domain.tld/auth'})

GET /auth HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Basic YTpi
Connection: keep-alive
Host: domain.tld
User-Agent: HTTPie/2.2.0
```

**Comment by maanuair** [comment]
Hi @jakubroztocil!

Thanks for the quick answer.

I'm really puzzled: reading your message, I just re-tried this morning, thinking that maybe the yesterday's end of day just befuddled me. 

So I copy paste your line:
```
$ https --offline -a 'a:b' domain.tld/auth | grep Authorization
Authorization: Basic YTpi
```
Ah, OK I cannot reproduce it either, this is the expected result.
At least it starts to make some sense now.

OK, so what happened yesterday? 🤔

Hmmm, was this intermediate test line, one I used yesterday, incorrect in the end?
Using bash's history, I found back this line:
```
$ echo \"$(https --offline -a 'a:b' domain.tld/auth | grep "Authorization" | cut -d' ' -f 3 | base64 -d)\"
" a:b"
```

And... What, the leading space just came back?!?

Maybe the line above has some defect that brings the extra space? 
I checked again, to be sure, removing the extra echo stuffs in last line.
```
$ https --offline -a 'a:b' domain.tld/auth | grep Authorization
Authorization: Basic wqBhOmI=
```

OK, so, same command line brings different results in the same 2 minutes.
Ouch.

🤨

It surely cannot be, they **must** be different, right?
And do you start to see where it leads us?

I re-copy the previous lines, the first is copied from my report, the second from your answer:
```
$ https --offline -a 'a:b' domain.tld/auth | grep Authorization # Mine! 
Authorization: Basic wqBhOmI=
$ https --offline -a 'a:b' domain.tld/auth | grep Authorization # Yours !
Authorization: Basic YTpi
```

OK, they **are** different, but one cannot see... Let put them in a file:
```
$ cat > actual.sh   # Copy from "my" command line 
https --offline -a 'a:b' domain.tld/auth | grep Authorization
^D
$ cat > expected.sh   # Copy from your answer
https --offline -a 'a:b' domain.tld/auth | grep Authorization
^D
```

Now, I check they still produce the different output:
```
$ chmod 755 expected.sh actual.sh
$ ./expected.sh
Authorization: Basic YTpi
$ ./actual.sh
Authorization: Basic wqBhOmI=
```

Now, the context is "captured", we're closer...
Start with a sanity check to help us, with `diff` (sanity for me, actually!):
```
$ diff actual.sh expected.sh
1c1
< https --offline -a 'a:b' domain.tld/auth | grep Authorization
---
> https --offline -a 'a:b' domain.tld/auth | grep Authorization
```

🤯

Yes, confirmed, they are different !
Still, not in a visible way, but this is progress to recover...

Now I know I'm not mad or something (phew!), so let's debunk this to the end.
Let's invoke our super-power, our friend `hexdump`:
```
$ hexdump -C actual.sh
00000000  68 74 74 70 73 20 2d 2d  6f 66 66 6c 69 6e 65 20  |https --offline |
00000010  2d 61 c2 a0 27 61 3a 62  27 20 64 6f 6d 61 69 6e  |-a..'a:b' domain|
00000020  2e 74 6c 64 2f 61 75 74  68 20 7c 20 67 72 65 70  |.tld/auth | grep|
00000030  20 41 75 74 68 6f 72 69  7a 61 74 69 6f 6e 0a     | Authorization.|
0000003f
$ hexdump -C expected.sh
00000000  68 74 74 70 73 20 2d 2d  6f 66 66 6c 69 6e 65 20  |https --offline |
00000010  2d 61 20 27 61 3a 62 27  20 64 6f 6d 61 69 6e 2e  |-a 'a:b' domain.|
00000020  74 6c 64 2f 61 75 74 68  20 7c 20 67 72 65 70 20  |tld/auth | grep |
00000030  41 75 74 68 6f 72 69 7a  61 74 69 6f 6e 0a        |Authorization.|
0000003e
```

That's it!

Can you see on second line?
`2d 61 c2 a0 27 61 (-a..'a:b')` **is** not `2d 61 20 27 61 (-a 'a:b')`.
What's this weird `c2 a0` sequence, instead of the expected `20` (aka: the regular, space ascii character)?

Searching for the sequence very quickly brings the culprit: it is... the Unicode character *Non Breaking Space* that broke my command! Also known as the *masquerade* space!

But why so much trouble ?
🥺

Well, now I remind...

I did copy/paste back and forth from an email I was writing. For some reason, an orignal space has been converted in a non breaking one, because I was using... a "wysiwyg" email composer, as a buffer to edit command lines. Gmail in my case, coud really be any non-text HTML composer, indeed.

And I knew that was bad.
And I had my emacs open, besides, offering for his loyal help, that I just ignored because "you know this is just a command line I send to a colleague, so I don't need a real editor, ah, wait, I retest again, and ah, a typo, so I copy back and forth.

Don't do that.

🤦‍♂️

If you ever have to send a CLI to someone, use a real editor/IDE, and only in the end you copy paste into your email.
NEVER the other way around.

Case closed, sorry for the "not a bug" report !

**Comment by jakubroztocil** [comment]
What a thriller, thanks for sharing! 😄
