### ISSUE TITLE
Feature request: support "http(s) request" from raw request file

### ISSUE THREAD

**Issue by snowman** [httpie/httpie#988]
From https://httpie.io/docs#offline-mode,

>   Generating raw requests that can be sent with any other client:
>   
>   ▶ RUN# 1. save a raw request to a file:
>   $ http --offline POST httpbin.org/post hello=world > request.http
>   ▶ RUN# 2. send it over the wire with, for example, the fantastic netcat tool:
>   $ nc httpbin.org 80 < request.http

## Expected

one can run `http request.http` or `https request.https` to reproduce some results.

**Comment by snowman** [comment]
so sorry, I don't know why there have two duplicate issues :cry: :sob:

**Comment by Almad** [comment]
No problem :)
