### ISSUE TITLE
is PySocks a dependancy ?

### ISSUE THREAD

**Issue by stonebig** [httpie/httpie#990]
With pip-20.3 new resolver coming, pysocks is enterpreted as mandatory dependancy from your https://github.com/httpie/httpie/blob/master/setup.py#L40..L41

`````
install_requires = [
    'requests[socks]>=2.22.0',`
`````

Is it what you wanted ?

( maybe it's a bug, not clear to me what the truth shall be:  https://github.com/pypa/pip/issues/9112#issuecomment-725444581)

**Comment by jakubroztocil** [comment]
@stonebig yes, this is intentional so that SOCKS support comes out of the box, and the user doesn’t have to install `PySocks` manually. Is it causing any issues?

**Comment by stonebig** [comment]
Not directly, it's just the Way you specify it in setup.py is imperfectly managed in pip toolset

**Comment by BoboTiG** [comment]
@stonebig do you have all answers you had looked for?

**Comment by isidentical** [comment]
Closing as the question was answered, @stonebig if you have any more questions feel free to create new issues.

**Comment by stonebig** [comment]
Sorry, I forgot to Close. Happy new Year to the team.
