### ISSUE TITLE
Proxy settings are ignored

### ISSUE THREAD

**Issue by dkasak** [httpie/httpie#992]
httpie 2.3.0 ignores both the `--proxy` flag and the `HTTP_PROXY` variable. The request succeeds but is made directly instead of through the proxy.

Examples:

```
http --verify=no --proxy=http:http://127.0.0.1:6666 URL foo=bar
```

```
HTTP_PROXY=http://127.0.0.1:6666 http --verify=no URL foo=bar
```

I also tried passing the arguments without `=` but the result is the same. The equivalent curl command works and is registered in the proxy:

```
curl -k --proxy http://127.0.0.1:6666 --data foo=bar URL
```

Has anyone ever encountered this? Where should I look next? I searched through existing issues but nothing popped up. I also tried running the command with `--debug -v` and sure enough, there's no mentions of proxies in the output:

```
>>> requests.request(**{'auth': None,
 'data': '{"foo": "bar"}',
 'headers': {'User-Agent': b'HTTPie/2.3.0', 'Accept': b'application/json, */*;q=0.5', 'Content-Type': b'application/json'},
 'method': 'post',
 'params': <generator object MultiValueOrderedDict.items at 0x7f1ff6d28c80>,
 'url': 'https://...'})
```

**Comment by ederin** [comment]
Httpie sends HTTP requests through HTTP proxy and HTTPS requests through HTTPS proxy. This behavior is consistent with behavior of underlying Requests library:

https://requests.readthedocs.io/en/v3.0.0/user/advanced/#proxies

It seems that you are trying to send HTTPS request through HTTP proxy. Did you try changing scheme to HTTPS?

`http --verify=no --proxy=https:http://127.0.0.1:6666 HTTPS-URL foo=bar`

**Comment by dkasak** [comment]
Ah, right, this is it. I've actually been bitten by this aspect of requests before, but I forgot about it. I'm used to `HTTP_PROXY` vs `HTTPS_PROXY` controlling which protocol will be spoken *to the proxy*, instead of saying what kind of requests will be redirected to it.

Thanks for reminding me.
