### ISSUE TITLE
send request which is saved in a text file

### ISSUE THREAD

**Issue by blueray453** [httpie/httpie#999]
my issue is, i need to see what exactly I am sending or receiving using cli where the request header is saved in a txt file.

I can do something like the following to send request (which is saved in `raw-http.txt`) and get response using `openssl`.

```
% echo '"'; cat raw-http.txt; echo '"'
"
GET / HTTP/1.0
Host: www.google.com

"
% cat raw-http.txt | openssl s_client -quiet -connect www.google.com:443 2>/dev/null
```
I skimmed through the documentation and it seems like `httpcat` can be used to do it. However, i am not sure whether it can be done using `httpie` or not. So, is it possible using `httpie`? If so, how can I do that?

Another question. http/2 headers are encoded using hpack. suppose my `raw-http2.txt` looks like:

```
:method:GET
:path:/
:scheme:https
:authority:www.google.com
user-agent:curl/7.58.0
accept:*/*
```
So, i think i have to do something like:
```
% cat raw-http.txt | encode-request | openssl s_client -quiet -connect www.google.com:443 2>/dev/null
```
can I do it using `httpie`? if so, how can I do that?

**Comment by isidentical** [comment]
As you've noticed, `httpcat` or `nc` is useful for constructing/sending manual requests on the terminal. `HTTPie` itself does not support it directly, as we do not support HTTP/2 at the moment.
